/**
 * Ashtakvarga Knowledge — sourced from Brihat Parashara Hora Shastra
 * Bindus table, Sarvashtakvarga, transit scoring rules
 */
export const ASHTAKVARGA_DATA = [
  { text: 'Ashtakvarga is a system of evaluating planetary strength through benefic points (bindus) contributed by 8 sources: Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, and Lagna. Each planet\'s Ashtakvarga chart has 12 signs with 0-8 bindus per sign. A sign with 4+ bindus is favorable for that planet\'s transit. The total of all 7 planets\' Ashtakvarga is called Sarvashtakvarga (SAV), with a maximum of 337 bindus across 12 signs.', category: 'ashtakvarga', topic: 'ashtakvarga_overview', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Sun\'s Ashtakvarga benefic points: Sun contributes bindus in houses 1,2,4,7,8,9,10,11 from itself. Moon contributes in 3,6,10,11 from Sun. Mars in 1,2,4,7,8,9,10,11. Mercury in 3,5,6,9,10,11,12. Jupiter in 5,6,9,11. Venus in 6,7,12. Saturn in 1,2,4,7,8,9,10,11. Lagna in 3,4,6,10,11,12 from Sun. Maximum possible: 48 bindus (usually 25-35 in practice).', category: 'ashtakvarga', topic: 'sun_ashtakvarga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Moon\'s Ashtakvarga benefic points: Sun in 3,6,7,8,10,11. Moon in 1,3,6,7,10,11. Mars in 2,3,5,6,9,10,11. Mercury in 1,3,4,5,7,8,10,11. Jupiter in 1,4,7,8,10,11,12. Venus in 3,4,5,7,9,10,11. Saturn in 3,5,6,11. Lagna in 3,6,10,11. Moon with 4+ bindus in a transit sign gives positive results; below 4 gives mental stress.', category: 'ashtakvarga', topic: 'moon_ashtakvarga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Sarvashtakvarga (SAV) interpretation: Total bindus per sign indicate the overall strength of that sign. Signs with 28+ SAV bindus are very favorable — planets transiting them give good results. Signs with 25-28 are average. Signs below 25 are weak — transits through them bring challenges. The highest SAV sign in a chart often indicates the area of greatest success.', category: 'ashtakvarga', topic: 'sarvashtakvarga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Ashtakvarga in transit prediction: When Saturn transits a sign with 4+ bindus in its own Ashtakvarga, the transit gives favorable results despite Saturn\'s general malefic nature. Jupiter transit through signs with 4+ Jupiter bindus gives prosperity, education, and spiritual growth. This is why the same transit (e.g., Saturn in Pisces) affects different people differently — their individual Ashtakvarga scores determine the outcome.', category: 'ashtakvarga', topic: 'ashtakvarga_transit', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Ashtakvarga Kakshya system: Each sign is divided into 8 equal parts (kakshyas) of 3°45\' each, ruled by Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon, and Lagna respectively. A planet transiting through a kakshya where it has a bindu gives favorable results during those specific degrees. This allows precise timing of transit effects within a sign.', category: 'ashtakvarga', topic: 'ashtakvarga_kakshya', source: 'Brihat Parashara Hora Shastra' },
];
