/**
 * Divisional Chart (Varga) Knowledge — sourced from Brihat Parashara Hora Shastra
 */
export const DIVISIONAL_CHART_DATA = [
  // ─── Overview ────────────────────────────────────────────────────────────────
  { text: 'Divisional charts (Varga charts) are sub-divisions of the zodiac that reveal specific life areas with microscopic precision beyond what the Rashi (D1) chart alone can show. Parashara describes the Shodashvarga system of 16 divisional charts, each created by dividing signs into smaller segments and mapping them to new signs. The strength of a planet is assessed by how many Vargas it occupies favorably — a concept called Vargabala — and planets strong across multiple divisional charts deliver their most reliable results.', category: 'divisional_charts', topic: 'varga_overview', source: 'Brihat Parashara Hora Shastra' },

  // ─── Navamsa (D9) ───────────────────────────────────────────────────────────
  { text: 'The Navamsa (D9) is the most important divisional chart after the Rashi chart and is created by dividing each sign into nine equal parts of 3°20\' each. It reveals the deeper truth of a planet\'s strength, the nature of one\'s spouse and marriage, dharmic inclinations, and spiritual life. The Navamsa Lagna indicates the native\'s inner character and the direction of their soul\'s purpose, while planets in the Navamsa show how their significations ultimately manifest in real life.', category: 'divisional_charts', topic: 'navamsa_d9', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Pushkara Navamsa refers to specific Navamsa divisions considered supremely auspicious — planets placed in these portions gain exceptional beneficence and the ability to bestow lasting good fortune. A Vargottama planet, one occupying the same sign in both Rashi and Navamsa, gains tremendous strength equivalent to being in its own sign and delivers its results with consistency and confidence. When the 7th lord of the Rashi chart is well-placed in Navamsa, or when benefics occupy the 7th house of the D9, marriage is harmonious and the spouse is supportive.', category: 'divisional_charts', topic: 'navamsa_d9_advanced', source: 'Brihat Parashara Hora Shastra' },

  // ─── Dashamsha (D10) ────────────────────────────────────────────────────────
  { text: 'The Dashamsha (D10) chart is created by dividing each sign into ten equal parts and specifically reveals career, profession, and status in society. The 10th lord of the Rashi chart examined in the D10, along with the Dashamsha Lagna lord, indicates the nature and success of one\'s professional life. Strong benefics in the Kendras of D10 grant authority and recognition in one\'s field, while malefics in the 10th house of D10 can indicate struggles, frequent job changes, or controversies in the workplace.', category: 'divisional_charts', topic: 'dashamsha_d10', source: 'Brihat Parashara Hora Shastra' },

  // ─── Saptamsha (D7) ────────────────────────────────────────────────────────
  { text: 'The Saptamsha (D7) chart divides each sign into seven equal parts and is the primary divisional chart for analyzing children, progeny, and creative works. The 5th house of the D7, its lord, and Jupiter\'s placement within this chart indicate the number of children, their wellbeing, and the native\'s relationship with them. Affliction to the D7 by malefics or a weak 5th lord in the Saptamsha can point to delays in childbirth or difficulties related to progeny.', category: 'divisional_charts', topic: 'saptamsha_d7', source: 'Brihat Parashara Hora Shastra' },

  // ─── Dwadashamsha (D12) ─────────────────────────────────────────────────────
  { text: 'The Dwadashamsha (D12) chart divides each sign into twelve equal parts and is used to examine parents, ancestry, and karmic inheritance from one\'s lineage. The 4th house of D12 represents the mother and the 9th house represents the father, and the condition of these houses and their lords reveals the health, longevity, and relationship dynamics with each parent. Planets in the D12 also shed light on the karmic debts and blessings carried forward through the family line.', category: 'divisional_charts', topic: 'dwadashamsha_d12', source: 'Brihat Parashara Hora Shastra' },

  // ─── Shodashamsha (D16) ─────────────────────────────────────────────────────
  { text: 'The Shodashamsha (D16) chart divides each sign into sixteen equal parts and governs vehicles, conveyances, comforts, luxuries, and property. A strong D16 with benefics in Kendras indicates ownership of fine vehicles and comfortable living conditions, while affliction suggests accidents, losses of property, or dissatisfaction with material comforts. The 4th house of D16 is especially significant for assessing happiness derived from houses, land, and personal possessions.', category: 'divisional_charts', topic: 'shodashamsha_d16', source: 'Brihat Parashara Hora Shastra' },

  // ─── Vimshamsha (D20) ──────────────────────────────────────────────────────
  { text: 'The Vimshamsha (D20) chart divides each sign into twenty equal parts and is dedicated to spiritual progress, worship, and sadhana practices. The placement of Jupiter, the 9th lord, and the 12th lord in D20 reveals the native\'s spiritual inclinations, the deity they are naturally drawn to, and the form of worship most beneficial for their evolution. A strong D20 with well-placed benefics indicates genuine spiritual advancement, while affliction may show obstacles or misdirection on the spiritual path.', category: 'divisional_charts', topic: 'vimshamsha_d20', source: 'Brihat Parashara Hora Shastra' },

  // ─── Chaturvimshamsha (D24) ────────────────────────────────────────────────
  { text: 'The Chaturvimshamsha (D24) chart divides each sign into twenty-four equal parts and governs education, learning, and academic achievements. The strength of Mercury, Jupiter, and the 4th and 5th lords in D24 determines the level and quality of education attained, areas of academic excellence, and success in examinations. Benefics in the Kendras of D24 indicate advanced degrees and scholarly recognition, while a weak D24 can point to interrupted education or difficulty in formal learning.', category: 'divisional_charts', topic: 'chaturvimshamsha_d24', source: 'Brihat Parashara Hora Shastra' },

  // ─── Shashtiamsha (D60) ────────────────────────────────────────────────────
  { text: 'The Shashtiamsha (D60) is the most microscopic divisional chart, dividing each sign into sixty equal parts of just 0°30\' each, and is considered the ultimate Varga for decoding past-life karma. Parashara states that the D60 holds the key to understanding why a soul has taken birth and what specific karmic debts or rewards it carries. Because of its extreme sensitivity to birth-time accuracy, even a difference of one minute can change the D60 Lagna, making precise birth records essential for its reliable interpretation.', category: 'divisional_charts', topic: 'shashtiamsha_d60', source: 'Brihat Parashara Hora Shastra' },

  // ─── Hora (D2) ─────────────────────────────────────────────────────────────
  { text: 'The Hora (D2) chart divides each sign into two halves — the Sun\'s Hora and the Moon\'s Hora — and is the primary divisional chart for assessing wealth and financial matters. Planets in the Sun\'s Hora indicate wealth acquired through self-effort, authority, and government connections, while planets in the Moon\'s Hora show wealth through public dealings, trade, and nurturing professions. A preponderance of planets in one Hora over the other reveals the dominant mode through which the native earns and accumulates resources.', category: 'divisional_charts', topic: 'hora_d2', source: 'Brihat Parashara Hora Shastra' },

  // ─── Drekkana (D3) ─────────────────────────────────────────────────────────
  { text: 'The Drekkana (D3) chart divides each sign into three equal parts of 10° each and primarily governs siblings, courage, and communication. The 3rd house of D3, its lord, and Mars\'s placement reveal the number of siblings, the native\'s relationship with them, and the overall courage and initiative one possesses. A well-fortified D3 indicates supportive siblings and bold self-expression, while affliction can point to conflicts with siblings or a lack of mental fortitude.', category: 'divisional_charts', topic: 'drekkana_d3', source: 'Brihat Parashara Hora Shastra' },

  // ─── Vargottama Concept ────────────────────────────────────────────────────
  { text: 'A planet is called Vargottama when it occupies the same sign in both the Rashi (D1) chart and the Navamsa (D9) chart, a condition that greatly amplifies its strength and reliability. Vargottama planets act as if they are in their own sign, delivering their results with clarity and consistency regardless of whether they are naturally benefic or malefic. A Vargottama Lagna lord is especially powerful, granting the native a strong sense of identity and purpose, while Vargottama malefics intensify both their challenging and protective qualities.', category: 'divisional_charts', topic: 'vargottama', source: 'Brihat Parashara Hora Shastra' },
];
