/**
 * Dosha Knowledge — sourced from Brihat Parashara Hora Shastra, Brihat Jataka, Lal Kitab
 */
export const DOSHA_DATA = [
  // ─── Mangal Dosha (Kuja Dosha) ────────────────────────────────────────────
  { text: 'Mangal Dosha (Kuja Dosha) occurs when Mars is placed in the 1st, 2nd, 4th, 7th, 8th, or 12th house from Lagna, Moon sign, or Venus. This dosha affects marriage and marital harmony. Mars in the 7th house is the most severe form — it can cause aggressive spouse, marital conflicts, or delayed marriage. Mars in the 1st house affects health and personality in marriage. Mars in the 8th house can cause obstacles in married life and longevity concerns for spouse.', category: 'dosha', topic: 'mangal_dosha', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Mangal Dosha cancellation (Dosha Bhanga) occurs in these conditions: 1) Mars is in its own sign (Aries, Scorpio) or exalted (Capricorn), 2) Mars is conjunct or aspected by Jupiter, 3) Mars is in the 2nd house in Gemini or Virgo, 4) Mars is in the 4th house in Aries or Scorpio, 5) Mars is in the 7th house in Cancer or Capricorn, 6) Mars is in the 8th house in Sagittarius or Pisces, 7) Mars is in the 12th house in Taurus or Libra, 8) Both partners have Mangal Dosha (cancels out).', category: 'dosha', topic: 'mangal_dosha_cancellation', source: 'Brihat Jataka' },
  { text: 'Remedies for Mangal Dosha: 1) Mangal Shanti Puja — worship of Lord Hanuman on Tuesdays, 2) Recite Mangal Mantra "Om Kraam Kreem Kraum Sah Bhaumaya Namah" 108 times daily, 3) Wear red coral (Moonga) gemstone in gold on ring finger after consulting astrologer, 4) Kumbh Vivah — symbolic marriage to a pot, banyan tree, or idol of Lord Vishnu before actual marriage, 5) Donate red lentils, red cloth, and jaggery on Tuesdays, 6) Fast on Tuesdays.', category: 'remedy', topic: 'mangal_dosha_remedy', source: 'Lal Kitab' },

  // ─── Kaal Sarp Dosha ──────────────────────────────────────────────────────
  { text: 'Kaal Sarp Dosha occurs when all seven planets (Sun through Saturn) are hemmed between Rahu and Ketu. There are 12 types based on the Rahu-Ketu axis: 1) Anant (Rahu in 1st), 2) Kulik (Rahu in 2nd), 3) Vasuki (Rahu in 3rd), 4) Shankhpal (Rahu in 4th), 5) Padma (Rahu in 5th), 6) Mahapadma (Rahu in 6th), 7) Takshak (Rahu in 7th), 8) Karkotak (Rahu in 8th), 9) Shankhchur (Rahu in 9th), 10) Ghatak (Rahu in 10th), 11) Vishdhar (Rahu in 11th), 12) Sheshnag (Rahu in 12th).', category: 'dosha', topic: 'kaal_sarp_dosha', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Kaal Sarp Dosha effects: Sudden setbacks in career, delayed marriage, financial instability, mysterious fears, recurring obstacles, and feeling of being stuck in life cycles. Partial Kaal Sarp (where one planet escapes the Rahu-Ketu axis) is less severe. The dosha weakens after age 33 (Rahu maturity) and may diminish significantly after age 42. Remedies include Kaal Sarp Puja at Trimbakeshwar (Nashik), Rahu-Ketu Shanti, and Nag Panchami worship.', category: 'dosha', topic: 'kaal_sarp_dosha', source: 'Brihat Jataka' },

  // ─── Pitra Dosha ──────────────────────────────────────────────────────────
  { text: 'Pitra Dosha (ancestral curse) is indicated when Sun is conjunct Rahu in any house, or when the 9th house lord is afflicted by Rahu, Saturn, or placed in 6th, 8th, or 12th house. Pitra Dosha indicates unresolved karma from ancestors. Effects include: difficulty conceiving children, repeated failures despite hard work, sudden health crises, family discord, and financial instability. The dosha is especially active during Pitru Paksha (September-October).', category: 'dosha', topic: 'pitra_dosha', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Remedies for Pitra Dosha: 1) Perform Shraddh ceremony during Pitru Paksha for departed ancestors, 2) Offer food to crows (representatives of ancestors) and Brahmins, 3) Recite Pitra Gayatri Mantra, 4) Plant a Peepal tree and water it regularly, 5) Donate food and clothes to the needy on Amavasya (new moon), 6) Perform Narayan Nagbali Puja at Trimbakeshwar, 7) Offer Pind Daan at Gaya or Varanasi.', category: 'remedy', topic: 'pitra_dosha_remedy', source: 'Lal Kitab' },

  // ─── Shani Dosha / Sade Sati ──────────────────────────────────────────────
  { text: 'Sade Sati occurs when Saturn transits through the 12th, 1st, and 2nd houses from natal Moon sign, lasting approximately 7.5 years. Each phase lasts 2.5 years: 1st phase (12th from Moon) — financial strain, hidden enemies, sleep issues; 2nd phase (over Moon) — most intense, emotional turbulence, health concerns, career changes; 3rd phase (2nd from Moon) — family issues, financial recovery begins. Sade Sati occurs 2-3 times in a lifetime.', category: 'dosha', topic: 'sade_sati', source: 'Phaladeepika' },
  { text: 'Remedies for Sade Sati and Saturn afflictions: 1) Recite Shani Mantra "Om Sham Shanicharaya Namah" 108 times on Saturdays, 2) Worship Lord Hanuman — the most powerful remedy for Saturn, 3) Wear blue sapphire (Neelam) ONLY after thorough astrological consultation, 4) Donate black sesame seeds, mustard oil, iron items, and dark blue/black clothes on Saturdays, 5) Feed black dogs and crows, 6) Light a sesame oil lamp under a Peepal tree on Saturday evenings, 7) Read or listen to Shani Chalisa.', category: 'remedy', topic: 'sade_sati_remedy', source: 'Lal Kitab' },

  // ─── Nadi Dosha ───────────────────────────────────────────────────────────
  { text: 'Nadi Dosha occurs in Kundli matching when both partners have the same Nadi (Adi/Vata, Madhya/Pitta, or Antya/Kapha). Nadi carries the highest 8 points in Ashtakoot matching, and same Nadi scores 0 points. Same Nadi is believed to cause health problems in offspring and constitutional incompatibility. However, Nadi Dosha is cancelled if: 1) Both have the same Rashi (Moon sign) but different Nakshatras, 2) Both have the same Nakshatra but different Rashi, 3) Both have the same Nakshatra but different Charan (pada).', category: 'dosha', topic: 'nadi_dosha', source: 'Muhurta Chintamani' },
];
