/**
 * House (Bhava) Knowledge — sourced from Brihat Parashara Hora Shastra, Phaladeepika, Saravali
 */
export const HOUSE_DATA = [
  // ─── 1st House (Lagna/Ascendant) ──────────────────────────────────────────
  { text: 'The 1st House (Lagna/Tanu Bhava) represents the self, physical body, personality, health, vitality, appearance, and general fortune. It is the most important house as it determines the framework of the entire chart. The sign rising at the time of birth becomes the Ascendant. A strong 1st house and its lord give good health, confidence, attractive personality, and overall success in life. Benefics in or aspecting the 1st house enhance its positive qualities.', category: 'houses', topic: '1st_house', source: 'Brihat Parashara Hora Shastra' },

  // ─── 2nd House ────────────────────────────────────────────────────────────
  { text: 'The 2nd House (Dhana Bhava) represents wealth, family, speech, food habits, face, right eye, and early childhood. It is the primary house of accumulated wealth and family lineage. Jupiter is the natural significator of the 2nd house. A strong 2nd house gives eloquent speech, wealth accumulation, harmonious family life, and good food habits. Malefics in the 2nd house can cause harsh speech, financial instability, and family discord. The 2nd house is also a maraka (death-inflicting) house.', category: 'houses', topic: '2nd_house', source: 'Phaladeepika' },

  // ─── 3rd House ────────────────────────────────────────────────────────────
  { text: 'The 3rd House (Sahaja Bhava) represents courage, younger siblings, short journeys, communication, hands, arms, shoulders, and self-effort (Parakrama). Mars is the natural significator. A strong 3rd house gives courage, good relationships with siblings, communication skills, and success through self-effort. It also governs writing, media, and artistic expression. The 3rd house is an Upachaya house — malefics here grow stronger with time and give positive results.', category: 'houses', topic: '3rd_house', source: 'Brihat Parashara Hora Shastra' },

  // ─── 4th House ────────────────────────────────────────────────────────────
  { text: 'The 4th House (Sukha Bhava) represents mother, emotional happiness, home, landed property, vehicles, education, chest/heart, and inner peace. Moon is the natural significator. A strong 4th house gives a comfortable home, good education, vehicles, property ownership, emotional contentment, and a nurturing mother. The 4th house is a Kendra (angular) house — benefics here give stability and comfort. Afflicted 4th house causes property disputes, unhappy home life, and chest ailments.', category: 'houses', topic: '4th_house', source: 'Phaladeepika' },

  // ─── 5th House ────────────────────────────────────────────────────────────
  { text: 'The 5th House (Putra Bhava) represents children, intelligence, creativity, romance, past life merit (Purva Punya), speculation, mantra siddhi, and higher mind. Jupiter is the natural significator. A strong 5th house gives intelligent children, creative talent, speculative gains, romantic fulfillment, and spiritual inclination. The 5th house is a Trikona (trine) — the house of fortune and divine grace. The 5th lord\'s placement determines the quality of one\'s progeny and creative expression.', category: 'houses', topic: '5th_house', source: 'Brihat Parashara Hora Shastra' },

  // ─── 6th House ────────────────────────────────────────────────────────────
  { text: 'The 6th House (Ripu/Roga Bhava) represents enemies, diseases, debts, obstacles, service, daily work routine, maternal uncle, and competition. Mars and Saturn are natural significators. A strong 6th house with strong lord gives victory over enemies, good health management, and success in competitive fields (law, medicine, military). The 6th house is a Dusthana (difficult house) but also an Upachaya — malefics here destroy enemies and disease. The 6th house is crucial for health predictions — the sign and planets here indicate disease-prone areas.', category: 'houses', topic: '6th_house', source: 'Phaladeepika' },

  // ─── 7th House ────────────────────────────────────────────────────────────
  { text: 'The 7th House (Kalatra Bhava) represents marriage, spouse, business partnerships, public dealings, foreign trade, and the lower abdomen. Venus is the natural significator for males and Jupiter for females. A strong 7th house gives a harmonious marriage, successful business partnerships, and good public reputation. The 7th house is a Kendra and maraka house — planets here strongly influence married life. The Navamsa (D9) chart must be analyzed alongside the 7th house for marriage predictions.', category: 'houses', topic: '7th_house', source: 'Brihat Parashara Hora Shastra' },

  // ─── 8th House ────────────────────────────────────────────────────────────
  { text: 'The 8th House (Ayu Bhava) represents longevity, death, transformation, inheritance, occult sciences, chronic illness, insurance, and sudden events. Saturn is the natural significator. A strong 8th house gives long life, inheritance, interest in occult, and ability to handle crises. An afflicted 8th house brings chronic diseases, accidents, sudden losses, and marital difficulties. The 8th house is the most mysterious house — it rules the hidden, the taboo, and transformation through crisis.', category: 'houses', topic: '8th_house', source: 'Phaladeepika' },

  // ─── 9th House ────────────────────────────────────────────────────────────
  { text: 'The 9th House (Dharma/Bhagya Bhava) represents father, guru, religion, higher philosophy, long journeys, fortune, dharma, and past life good karma. Jupiter and Sun are natural significators. The 9th house is the most auspicious Trikona — it represents divine grace and luck. A strong 9th house gives a virtuous father, spiritual guru, foreign travel, higher education, and overall good fortune. The 9th lord is called the lord of fortune — its placement determines one\'s luck quotient.', category: 'houses', topic: '9th_house', source: 'Brihat Parashara Hora Shastra' },

  // ─── 10th House ───────────────────────────────────────────────────────────
  { text: 'The 10th House (Karma Bhava) represents career, profession, social status, reputation, government, authority, and life purpose. Sun, Mercury, Jupiter, and Saturn are natural significators. The 10th house is the most visible house — it determines one\'s public image and career direction. A strong 10th house gives a successful career, high social status, government connections, and professional recognition. The Dasamsa (D10) chart provides deeper career analysis.', category: 'houses', topic: '10th_house', source: 'Phaladeepika' },
  { text: 'Career selection through the 10th house: Sun in 10th suggests government/administrative careers. Moon suggests public-facing or hospitality roles. Mars suggests military, surgery, engineering, or sports. Mercury suggests communication, writing, commerce, or IT. Jupiter suggests teaching, law, finance, or religious work. Venus suggests arts, entertainment, luxury goods, or diplomacy. Saturn suggests labor, construction, agriculture, or social work.', category: 'houses', topic: '10th_house_career', source: 'Phaladeepika' },

  // ─── 11th House ───────────────────────────────────────────────────────────
  { text: 'The 11th House (Labha Bhava) represents gains, income, elder siblings, friends, social network, fulfillment of desires, and the left ear. Jupiter is the natural significator. The 11th house is the house of gains and achievement — it shows what one receives in life. A strong 11th house gives abundant income, supportive friends, fulfilled desires, and gains from multiple sources. The 11th house is an Upachaya — planets here grow stronger with age.', category: 'houses', topic: '11th_house', source: 'Brihat Parashara Hora Shastra' },

  // ─── 12th House ───────────────────────────────────────────────────────────
  { text: 'The 12th House (Vyaya Bhava) represents losses, expenses, foreign lands, spirituality, moksha (liberation), sleep, bed pleasures, isolation, and the left eye. Saturn and Ketu are natural significators. A strong 12th house gives spiritual liberation, foreign settlement, peaceful sleep, and charitable disposition. An afflicted 12th house causes excessive expenses, imprisonment, hospitalization, insomnia, and self-undoing. The 12th house from any house represents the loss of that house\'s significations.', category: 'houses', topic: '12th_house', source: 'Phaladeepika' },
];
