/**
 * Kundli Matching (Guna Milan) Knowledge — sourced from Muhurta Chintamani, Brihat Parashara Hora Shastra
 */
export const MATCHING_DATA = [
  { text: 'Ashtakoot Guna Milan is the Vedic system of matching horoscopes for marriage compatibility. It evaluates 8 aspects (Kootas) with a total of 36 points. A score of 18 or above (50%) is considered acceptable for marriage. Below 18 is considered incompatible. Scores above 25 indicate excellent compatibility. However, Guna Milan alone is insufficient — Mangal Dosha, Bhakoot Dosha, and Nadi Dosha must be evaluated separately.', category: 'matching', topic: 'ashtakoot_overview', source: 'Muhurta Chintamani' },

  { text: 'Varna Koota (1 point): Evaluates spiritual compatibility and ego levels. The four Varnas in descending order: Brahmin (Cancer, Scorpio, Pisces), Kshatriya (Aries, Leo, Sagittarius), Vaishya (Taurus, Virgo, Capricorn), Shudra (Gemini, Libra, Aquarius). The groom\'s Varna should be equal or higher than the bride\'s for full point. This is the least weighted factor.', category: 'matching', topic: 'varna_koota', source: 'Muhurta Chintamani' },

  { text: 'Vasya Koota (2 points): Evaluates mutual attraction and control dynamics. Each sign has natural Vasya (attraction) relationships. For example: Aries is Vasya to Leo; Cancer is Vasya to Scorpio. When both signs are mutually Vasya, full 2 points are awarded. When one is Vasya to the other, 1 point. When neither is Vasya, 0 points. This factor indicates who will have more influence in the relationship.', category: 'matching', topic: 'vasya_koota', source: 'Muhurta Chintamani' },

  { text: 'Tara Koota (3 points): Evaluates health and longevity compatibility based on birth Nakshatras. Count from bride\'s Nakshatra to groom\'s and divide by 9. If the remainder is 1 (Janma), 2 (Sampat), 4 (Kshema), 6 (Sadhana), 8 (Mitra), or 0 (Ati-Mitra), it is auspicious. Remainders 3 (Vipat), 5 (Pratyak), 7 (Vadha), or 9 (Vadha) are inauspicious. Check both directions — if at least one direction is favorable, 1.5 points; both favorable gives 3 points.', category: 'matching', topic: 'tara_koota', source: 'Muhurta Chintamani' },

  { text: 'Yoni Koota (4 points): Evaluates sexual and physical compatibility. Each Nakshatra is assigned an animal yoni: Horse, Elephant, Sheep, Snake, Dog, Cat, Rat, Cow, Buffalo, Tiger, Deer, Monkey, Mongoose, Lion. Natural enemies score 0 (e.g., Cat-Rat, Snake-Mongoose), neutral pairs score 2, friendly pairs score 3, same yoni scores 4 points. This factor is especially important for physical intimacy compatibility.', category: 'matching', topic: 'yoni_koota', source: 'Muhurta Chintamani' },

  { text: 'Graha Maitri Koota (5 points): Evaluates mental and intellectual compatibility based on the lords of both Moon signs. When both Rashi lords are friends, 5 points. One friendly and one neutral gives 4. Both neutral gives 3. One friendly and one enemy gives 1. One neutral and one enemy gives 0.5. Both enemies gives 0. Planet friendships: Sun friends with Moon, Mars, Jupiter; enemies with Venus, Saturn. Moon friends with Sun, Mercury; enemy with none. Mars friends with Sun, Moon, Jupiter; enemies with Mercury. This is a crucial factor for long-term mental compatibility.', category: 'matching', topic: 'graha_maitri_koota', source: 'Muhurta Chintamani' },

  { text: 'Gana Koota (6 points): Evaluates temperament and nature compatibility. Three Ganas: Deva (divine/sattvic), Manushya (human/rajasic), Rakshasa (demonic/tamasic). Same Gana: 6 points. Deva-Manushya: 5 points. Deva-Rakshasa: 1 point. Manushya-Rakshasa: 0 points. Rakshasa-Rakshasa: 6 points (they understand each other). Gana mismatch is a significant factor — Deva-Rakshasa combination often causes fundamental temperament clashes in marriage.', category: 'matching', topic: 'gana_koota', source: 'Muhurta Chintamani' },

  { text: 'Bhakoot Koota (7 points): Evaluates emotional compatibility and financial prosperity. The Moon sign positions relative to each other determine the score. 2/12, 5/9, 6/8 combinations score 0 and indicate Bhakoot Dosha. 2/12 causes financial problems. 6/8 causes health issues and separation. 5/9 causes issues with progeny. However, Bhakoot Dosha is cancelled when the lords of both Moon signs are friends, or when they are the same planet. This is the second most important factor.', category: 'matching', topic: 'bhakoot_koota', source: 'Muhurta Chintamani' },

  { text: 'Nadi Koota (8 points): The most important factor with highest points. Evaluates health compatibility and genetic compatibility of offspring. Three Nadis: Adi (Vata), Madhya (Pitta), Antya (Kapha). Same Nadi scores 0 and is considered a serious dosha that may cause health problems in children. Different Nadi scores 8 points. Nadi Dosha cancellation: same Rashi but different Nakshatra, same Nakshatra but different Rashi, or same Nakshatra but different Pada.', category: 'matching', topic: 'nadi_koota', source: 'Muhurta Chintamani' },

  { text: 'Beyond Ashtakoot matching, these additional factors must be checked: 1) Mangal Dosha — Mars placement compatibility, 2) Longevity assessment — both charts should indicate similar lifespan, 3) Strength of 7th house and its lord in both charts, 4) Venus and Jupiter strength (significators of marriage), 5) Dasha compatibility — both should not be running difficult Dashas simultaneously, 6) Navamsa (D9) chart compatibility, 7) Planets in 2nd and 8th houses (maraka sthanas).', category: 'matching', topic: 'additional_factors', source: 'Brihat Parashara Hora Shastra' },
];
