/**
 * Muhurat (Auspicious Timing) Knowledge — sourced from Muhurta Chintamani, Brihat Samhita, Dharma Sindhu
 */
export const MUHURAT_DATA = [
  // ─── Muhurat Overview ────────────────────────────────────────────────────
  { text: 'Muhurat (Electional Astrology) is the branch of Vedic astrology that determines the most auspicious time to begin important activities. It ensures cosmic alignment supports the endeavor\'s success by harmonizing celestial energies with human intention. The five essential elements (Panchanga) considered in Muhurat selection are: Tithi (lunar day), Vara (weekday), Nakshatra (lunar mansion), Yoga (luni-solar combination), and Karana (half-tithi). A good Muhurat requires favorable alignment of all five elements, with special emphasis on Nakshatra and Tithi for most activities.', category: 'muhurat', topic: 'muhurat_overview', source: 'Muhurta Chintamani' },

  // ─── Muhurat Types by Purpose ────────────────────────────────────────────
  { text: 'Vivah Muhurat (Marriage): The best tithis for marriage are 2nd, 3rd, 5th, 7th, 10th, 11th, and 13th of Shukla Paksha. Favorable nakshatras include Rohini, Mrigashira, Magha, Uttara Phalguni, Hasta, Swati, Anuradha, Moola, Uttara Ashadha, Uttara Bhadrapada, and Revati. The months of Magha, Phalguna, Vaishakha, and Jyeshtha are preferred. Avoid Bhadra (Vishti Karana), Rahu Kaal, eclipses, and the lunar months of Ashwin and Pausha. Jupiter and Venus must not be combust, and the 7th and 8th houses from the Muhurat Lagna should be free of malefics.', category: 'muhurat', topic: 'vivah_muhurat', source: 'Muhurta Chintamani' },
  { text: 'Griha Pravesh Muhurat (Housewarming): The native should enter a new home when Jupiter, Venus, and Mercury are strong and not combust. Best nakshatras are Uttara Phalguni, Uttara Ashadha, Uttara Bhadrapada, Rohini, Mrigashira, Swati, Anuradha, Dhanishta, Shatabhisha, and Revati. Shukla Paksha (waxing Moon) is essential, with the 2nd, 3rd, 5th, 7th, 10th, 11th, or 13th tithis preferred. The 4th house of the Muhurat chart should be strong, free of malefic influence, and the Moon should not occupy the 6th, 8th, or 12th house from the Muhurat Lagna.', category: 'muhurat', topic: 'griha_pravesh_muhurat', source: 'Dharma Sindhu' },
  { text: 'Vyapara Muhurat (Business Start): Starting a new business or commercial venture requires Mercury to be strong and well-placed, as it governs trade and commerce. Best nakshatras are Ashwini, Rohini, Mrigashira, Punarvasu, Pushya, Hasta, Chitra, Swati, Anuradha, Shravana, Dhanishta, and Revati. Wednesday, Thursday, and Friday are the most favorable weekdays. The 10th house of the Muhurat Lagna should be strong, the Lagna lord well-placed, and the 7th house (partnerships) free of severe affliction.', category: 'muhurat', topic: 'vyapara_muhurat', source: 'Brihat Samhita' },
  { text: 'Vidya Arambha Muhurat (Education Start): Commencement of education or learning favors nakshatras ruled by Mercury, Jupiter, and Venus — particularly Ashwini, Punarvasu, Pushya, Hasta, Swati, Shravana, Dhanishta, Shatabhisha, and Revati. The best tithis are 2nd, 3rd, 5th, 10th, and 11th of Shukla Paksha. Wednesday and Thursday are the most auspicious weekdays. Jupiter should aspect the Lagna or the 5th house (house of learning), and the 2nd house (speech) and 4th house (formal education) should be unafflicted.', category: 'muhurat', topic: 'vidya_arambha_muhurat', source: 'Muhurta Chintamani' },
  { text: 'Yatra Muhurat (Travel): For safe and successful travel, the Moon should be strong and not in the 8th house from the Lagna. Favorable nakshatras for travel are Ashwini, Mrigashira, Punarvasu, Pushya, Hasta, Anuradha, Shravana, and Revati. Avoid travel on Tuesdays and Saturdays unless those days are specifically favorable in the individual\'s chart. One should not travel in the direction of the daily Shula (planetary spear): East on Monday and Saturday, North on Tuesday and Wednesday, South on Thursday, and West on Friday and Sunday.', category: 'muhurat', topic: 'yatra_muhurat', source: 'Brihat Samhita' },
  { text: 'Mundana Muhurat (Head Shaving/Naming Ceremony): A baby\'s first head shaving (Chudakarana) should be performed in the 1st or 3rd year, on an auspicious tithi during Shukla Paksha. Favorable nakshatras include Ashwini, Mrigashira, Punarvasu, Pushya, Hasta, Chitra, Swati, Shravana, and Revati. The naming ceremony (Namakarana) is performed on the 11th or 12th day after birth, with the Moon strong and in a favorable nakshatra. Monday, Wednesday, Thursday, and Friday are preferred weekdays for both ceremonies.', category: 'muhurat', topic: 'mundana_muhurat', source: 'Dharma Sindhu' },
  { text: 'Property Purchase Muhurat: Buying land or property requires a strong 4th house in the Muhurat chart, with its lord well-placed and unafflicted. Favorable nakshatras are the fixed (Dhruva) group — Rohini, Uttara Phalguni, Uttara Ashadha, and Uttara Bhadrapada — as they signify permanence and stability. Thursday and Friday are the best weekdays. Mars should not afflict the 4th house, Saturn should not be retrograde in Kendras, and the Lagna lord should ideally be in a Kendra or Trikona to ensure lasting benefit from the purchase.', category: 'muhurat', topic: 'property_purchase_muhurat', source: 'Muhurta Chintamani' },

  // ─── Auspicious Nakshatras for Activities ────────────────────────────────
  { text: 'Fixed (Dhruva) and Soft (Mridu) Nakshatras: The four fixed nakshatras — Rohini, Uttara Phalguni, Uttara Ashadha, and Uttara Bhadrapada — are ideal for permanent undertakings such as laying foundations, property purchase, planting trees, and coronations, as their energy promotes stability and endurance. The four soft nakshatras — Mrigashira, Chitra, Anuradha, and Revati — are best suited for artistic pursuits, learning music and dance, romance, friendship, wearing new clothes, and activities requiring grace and refinement.', category: 'muhurat', topic: 'dhruva_mridu_nakshatras', source: 'Muhurta Chintamani' },
  { text: 'Movable (Chara) and Sharp (Tikshna) Nakshatras: The movable nakshatras — Punarvasu, Swati, Shravana, Dhanishta, and Shatabhisha — favor activities involving movement and change such as travel, vehicle purchase, gardening, and starting journeys. They support new beginnings that involve transition. The sharp (Tikshna) nakshatras — Moola, Ardra, Ashlesha, and Jyeshtha — carry intense, piercing energy suited for surgery, filing lawsuits, acts of separation or destruction, tantric practices, and invoking fierce deities. These should be avoided for auspicious ceremonies like marriage.', category: 'muhurat', topic: 'chara_tikshna_nakshatras', source: 'Brihat Samhita' },

  // ─── Choghadiya System ───────────────────────────────────────────────────
  { text: 'The Choghadiya system divides each day and night into eight equal slots (approximately 1.5 hours each depending on sunrise/sunset), each ruled by a planet with a distinct quality. The seven types are: Amrit (Moon, most auspicious — ideal for all good works), Shubh (Jupiter, auspicious — good for religious and educational acts), Labh (Mercury, profitable — good for business and financial matters), Char (Venus, neutral/movable — suitable for travel), Rog (Mars, inauspicious — associated with disease, avoid medical procedures), Kaal (Saturn, inauspicious — avoid important beginnings), and Udveg (Sun, inauspicious — causes anxiety, avoid new ventures). Day Choghadiya begins at sunrise and night Choghadiya at sunset.', category: 'muhurat', topic: 'choghadiya_system', source: 'Muhurta Chintamani' },

  // ─── Hora System ─────────────────────────────────────────────────────────
  { text: 'The Hora system assigns each hour of the day to a planetary ruler in the Chaldean order: Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon. The first hora of each day belongs to the day\'s ruling planet (Sun for Sunday, Moon for Monday, Mars for Tuesday, etc.). Sun Hora favors government work and authority matters; Moon Hora is good for travel and public dealings; Mars Hora suits surgery, competition, and land matters; Mercury Hora benefits trade, education, and communication; Jupiter Hora is ideal for religious acts, marriage, and finance; Venus Hora supports arts, romance, and luxury purchases; Saturn Hora is suited for labor, agriculture, and dealing with iron or oil.', category: 'muhurat', topic: 'hora_system', source: 'Brihat Samhita' },

  // ─── Inauspicious Periods to Avoid ───────────────────────────────────────
  { text: 'Rahu Kaal is an inauspicious period of approximately 1.5 hours each day ruled by Rahu, during which new ventures should not be started. It falls on different times depending on the weekday: Monday 7:30-9:00, Saturday 9:00-10:30, Friday 10:30-12:00, Wednesday 12:00-1:30, Thursday 1:30-3:00, Tuesday 3:00-4:30, Sunday 4:30-6:00 (approximate, varies by sunrise). Gulika Kaal (son of Saturn) is similarly inauspicious and should be avoided for auspicious activities. Yama Gandanta refers to the dangerous junctional points between water and fire signs (Cancer-Leo, Scorpio-Sagittarius, Pisces-Aries) where the Moon\'s transit is considered highly unfavorable.', category: 'muhurat', topic: 'rahu_kaal_gulika', source: 'Dharma Sindhu' },
  { text: 'Bhadra (Vishti Karana) occurs when the 2nd or 7th Karana of certain tithis is active — it is considered highly inauspicious for starting any auspicious work, travel, or ceremonies. Panchaka refers to the five nakshatras from Dhanishta to Revati (Dhanishta, Shatabhisha, Purva Bhadrapada, Uttara Bhadrapada, Revati) during which death rites, south-facing travel, roof construction, and fuel-gathering are prohibited. Eclipse periods (Grahan) render all auspicious activities forbidden from the start of the Sutak period until the eclipse ends. Adhik Maas (intercalary month) is generally avoided for marriage, upanayana, and other Shodasha Samskaras, though it is considered excellent for spiritual practices and charity.', category: 'muhurat', topic: 'bhadra_panchaka_eclipse', source: 'Dharma Sindhu' },

  // ─── Abhijit Muhurat ─────────────────────────────────────────────────────
  { text: 'Abhijit Muhurat is the universally auspicious 48-minute window occurring at local solar midday, approximately 24 minutes before and after noon. It is named after the Abhijit nakshatra (Vega star) and is considered so powerful that it neutralizes most other doshas present in the Panchanga. Abhijit Muhurat is suitable for virtually all auspicious activities — starting a business, signing contracts, beginning travel, performing rituals, and initiating any important work. However, it is not recommended for marriage ceremonies, as the Sun\'s peak strength at midday is considered too fierce for the gentle nature of the wedding ritual. This Muhurat is universally available every day except on Wednesdays, when it is traditionally considered void.', category: 'muhurat', topic: 'abhijit_muhurat', source: 'Muhurta Chintamani' },
];
