/**
 * Nakshatra Knowledge — sourced from Brihat Parashara Hora Shastra, Muhurta Chintamani
 */
export const NAKSHATRA_DATA = [
  { text: 'Ashwini Nakshatra (0°-13°20\' Aries) — Ruled by Ketu. Deity: Ashwini Kumaras (divine physicians). Symbol: Horse head. Gana: Deva. Nadi: Vata. Qualities: Quick healing ability, speed, pioneering spirit, medical aptitude. Career: Medicine, emergency services, transportation, horse-related activities. Health: Head injuries, fevers. This is the first Nakshatra — represents new beginnings and quick action.', category: 'nakshatras', topic: 'ashwini', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Bharani Nakshatra (13°20\'-26°40\' Aries) — Ruled by Venus. Deity: Yama (god of death/dharma). Symbol: Yoni (female reproductive organ). Gana: Manushya. Nadi: Pitta. Qualities: Creative power, transformation, endurance, fertility. Career: Arts, entertainment, judiciary, reproductive health. Bharani represents the power of creation and the cycle of birth-death-rebirth.', category: 'nakshatras', topic: 'bharani', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Krittika Nakshatra (26°40\' Aries - 10° Taurus) — Ruled by Sun. Deity: Agni (fire god). Symbol: Razor/flame. Gana: Rakshasa. Nadi: Kapha. Qualities: Sharp intellect, purification, authority, cooking/fire-related skills. Career: Military, cooking/culinary arts, goldsmithing, spiritual purification. Krittika spans two signs — the Aries portion is more aggressive, while the Taurus portion is more nurturing.', category: 'nakshatras', topic: 'krittika', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Rohini Nakshatra (10°-23°20\' Taurus) — Ruled by Moon. Deity: Brahma (creator). Symbol: Chariot/ox cart. Gana: Manushya. Nadi: Kapha. Qualities: Beauty, fertility, growth, artistic talent, material abundance. Career: Agriculture, fashion, cosmetics, real estate, music. Rohini is considered the most beautiful and fertile Nakshatra. Moon is exalted here. Krishna was born in Rohini Nakshatra.', category: 'nakshatras', topic: 'rohini', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Mrigashira Nakshatra (23°20\' Taurus - 6°40\' Gemini) — Ruled by Mars. Deity: Soma (Moon god). Symbol: Deer head. Gana: Deva. Nadi: Pitta. Qualities: Curiosity, searching nature, gentleness, research ability. Career: Research, textiles, travel, perfumery, music. Mrigashira natives are eternal seekers — always searching for the perfect knowledge, partner, or truth.', category: 'nakshatras', topic: 'mrigashira', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Ardra Nakshatra (6°40\'-20° Gemini) — Ruled by Rahu. Deity: Rudra (storm god). Symbol: Teardrop/diamond. Gana: Manushya. Nadi: Vata. Qualities: Intellectual power, transformation through destruction, research, technology. Career: Technology, software, electronics, pharmaceutical research, storm chasing. Ardra represents the power of effort and transformation through storms of life.', category: 'nakshatras', topic: 'ardra', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Punarvasu Nakshatra (20° Gemini - 3°20\' Cancer) — Ruled by Jupiter. Deity: Aditi (mother of gods). Symbol: Quiver of arrows/house. Gana: Deva. Nadi: Vata. Qualities: Renewal, return to origins, optimism, nurturing, philosophical nature. Career: Teaching, counseling, hospitality, publishing, import-export. Lord Rama was born in Punarvasu. This Nakshatra gives the power to return and restore.', category: 'nakshatras', topic: 'punarvasu', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Pushya Nakshatra (3°20\'-16°40\' Cancer) — Ruled by Saturn. Deity: Brihaspati (Jupiter/priest of gods). Symbol: Cow udder/flower. Gana: Deva. Nadi: Pitta. Qualities: Nourishment, prosperity, spiritual authority, patience. Career: Dairy, food industry, priesthood, counseling, government service. Pushya is considered the most auspicious Nakshatra for starting ventures — Pushya Nakshatra day is ideal for purchasing gold, starting businesses, and initiating important work.', category: 'nakshatras', topic: 'pushya', source: 'Muhurta Chintamani' },
  { text: 'The 27 Nakshatras are divided into three groups of 9 for Vimshottari Dasha calculation. Each Nakshatra spans 13°20\' of the zodiac and is ruled by one of the 9 planets: Ketu (Ashwini, Magha, Moola), Venus (Bharani, Purva Phalguni, Purva Ashadha), Sun (Krittika, Uttara Phalguni, Uttara Ashadha), Moon (Rohini, Hasta, Shravana), Mars (Mrigashira, Chitra, Dhanishta), Rahu (Ardra, Swati, Shatabhisha), Jupiter (Punarvasu, Vishakha, Purva Bhadrapada), Saturn (Pushya, Anuradha, Uttara Bhadrapada), Mercury (Ashlesha, Jyeshtha, Revati).', category: 'nakshatras', topic: 'nakshatra_lords', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Nakshatra compatibility in marriage uses the Gana (temperament) system: Deva Gana (divine) — Ashwini, Mrigashira, Punarvasu, Pushya, Hasta, Swati, Anuradha, Shravana, Revati. Manushya Gana (human) — Bharani, Rohini, Ardra, Purva Phalguni, Uttara Phalguni, Purva Ashadha, Uttara Ashadha, Purva Bhadrapada, Uttara Bhadrapada. Rakshasa Gana (demonic) — Krittika, Ashlesha, Magha, Chitra, Vishakha, Jyeshtha, Moola, Dhanishta, Shatabhisha. Best compatibility: same Gana. Deva-Manushya is acceptable. Deva-Rakshasa is considered incompatible.', category: 'nakshatras', topic: 'nakshatra_compatibility', source: 'Muhurta Chintamani' },
];
