/**
 * Palmistry Knowledge — sourced from Samudrika Shastra, Hast Rekha Vigyan
 */
export const PALMISTRY_DATA = [
  // ─── Palmistry Overview ──────────────────────────────────────────────────
  { text: 'Samudrika Shastra is the ancient Indian science of body features and palm reading, with roots in Vedic literature dating back over 5,000 years. The dominant (active) hand reflects the current and future life shaped by personal choices, while the passive (non-dominant) hand reveals inherited traits, potential, and past-life karma. A complete palm reading considers both hands together — differences between them indicate how much the native has evolved from their innate tendencies. Interpretation should always be holistic, combining lines, mounts, finger proportions, and hand shape rather than relying on any single feature.', category: 'palmistry', topic: 'overview', source: 'Samudrika Shastra' },

  // ─── Major Palm Lines ────────────────────────────────────────────────────
  { text: 'The Heart Line (Hridaya Rekha) runs horizontally across the upper palm below the fingers and governs emotions, relationships, and cardiac health. A long, deep, curved Heart Line reaching the Mount of Jupiter indicates a warm, expressive, and idealistic approach to love, while a straight Heart Line suggests a more rational and reserved emotional nature. A chained Heart Line indicates emotional turbulence and sensitivity in relationships; breaks in the line signify heartbreak or major emotional disruptions at the corresponding age. Forked endings (known as the "writer\'s fork") show a balance between emotion and reason.', category: 'palmistry', topic: 'heart_line', source: 'Hast Rekha Vigyan' },
  { text: 'The Head Line (Mastishk Rekha) runs horizontally across the middle of the palm and represents intellect, reasoning ability, and decision-making style. A long, straight Head Line indicates analytical, logical, and methodical thinking, while a curved or sloping line toward the Mount of Moon shows imagination, creativity, and intuitive decision-making. A short Head Line denotes a practical, focused thinker who prefers action over deliberation. Breaks in the Head Line suggest mental crises or significant shifts in thinking at those ages; islands indicate periods of mental stress, confusion, or lack of concentration.', category: 'palmistry', topic: 'head_line', source: 'Hast Rekha Vigyan' },
  { text: 'The Life Line (Jeevan Rekha) arcs around the base of the thumb and represents vitality, physical energy, and major life changes — it does NOT indicate the length of life. A deep, well-defined Life Line shows robust physical constitution and abundant energy, while a faint or thin line indicates a person susceptible to fatigue and low vitality. A wide arc sweeping toward the center of the palm signifies enthusiasm and a love for life, whereas a line hugging close to the thumb suggests limited energy and a cautious personality. Branches rising upward from the Life Line denote periods of achievement; downward branches signify losses or challenges.', category: 'palmistry', topic: 'life_line', source: 'Hast Rekha Vigyan' },
  { text: 'The Fate Line (Shani Rekha or Saturn Line) runs vertically from the base of the palm toward the middle finger and governs career, destiny, and the influence of external circumstances on one\'s life. A strong, unbroken Fate Line from the wrist to the Mount of Saturn indicates a clear, self-directed career path with steady success. A Fate Line beginning from the Life Line shows a self-made individual, while one originating from the Mount of Moon suggests a career influenced by public favor or external forces. Breaks in the Fate Line indicate career changes; multiple parallel Fate Lines suggest dual careers or diverse income sources. Timing is read from the wrist (age 0) upward to the fingers (age 75+).', category: 'palmistry', topic: 'fate_line', source: 'Hast Rekha Vigyan' },
  { text: 'The Sun Line (Surya Rekha or Apollo Line) runs vertically toward the ring finger and indicates fame, success, creative fulfillment, and public recognition. A well-defined Sun Line enhances any career indicated by the Fate Line, bringing satisfaction, reputation, and wealth through talent. The Sun Line appearing after age 30 (mid-palm) is very common and suggests recognition arriving in the second half of life. Absence of a Sun Line does not mean failure — it simply indicates that success comes through persistent effort rather than public acclaim. Multiple Sun Lines suggest versatile talents but scattered focus.', category: 'palmistry', topic: 'sun_line', source: 'Hast Rekha Vigyan' },
  { text: 'The Mercury Line (Swasthya Rekha or Health Line) runs diagonally from below the little finger toward the lower palm and reveals health conditions, business acumen, and communication ability. Ironically, the absence of this line is the best sign, indicating robust health. A wavy Mercury Line suggests digestive or liver problems, while islands on this line indicate periods of hospitalization or chronic illness. When the Mercury Line is straight and clear, it enhances business skills, persuasion, and scientific aptitude. This line is also called the Line of Liver or Line of Business in Western palmistry traditions.', category: 'palmistry', topic: 'mercury_line', source: 'Hast Rekha Vigyan' },
  { text: 'Marriage Lines (Vivah Rekha) are short horizontal lines found on the edge of the palm between the base of the little finger and the Heart Line. The number of deep, prominent lines indicates significant long-term relationships or marriages; faint lines represent minor attachments. A long, clear Marriage Line suggests a strong, lasting union, while a line that curves downward toward the Heart Line may indicate the partner\'s health challenges or emotional disappointment. A forked Marriage Line can signify separation or divergent interests. The position relative to the Heart Line indicates approximate timing — closer to the Heart Line means earlier in life, closer to the little finger means later.', category: 'palmistry', topic: 'marriage_lines', source: 'Hast Rekha Vigyan' },

  // ─── Mounts of the Palm ──────────────────────────────────────────────────
  { text: 'The Mount of Jupiter (below the index finger) represents ambition, leadership, self-confidence, and spiritual inclination. A well-developed Jupiter mount indicates a natural leader with a strong desire for knowledge and social status. The Mount of Saturn (below the middle finger) governs discipline, responsibility, wisdom, and introspection — a prominent Saturn mount indicates a serious, studious nature with inclination toward research and solitude. The Mount of Apollo or Sun (below the ring finger) rules creativity, fame, artistic talent, and cheerfulness; a strong Apollo mount is found in artists, performers, and those who attract public admiration. The Mount of Mercury (below the little finger) controls communication, commerce, scientific ability, and wit — a well-developed Mercury mount indicates skill in business, medicine, or oratory.', category: 'palmistry', topic: 'mounts_fingers', source: 'Samudrika Shastra' },
  { text: 'The Mount of Venus (fleshy base of the thumb) is the largest mount and governs love, passion, physical vitality, sensuality, and family bonds. A well-developed, firm Venus mount indicates warmth, generosity, and strong romantic nature, while a flat Venus mount suggests coldness and low vitality. The Mount of Moon or Luna (opposite Venus, on the percussion edge below the little finger) rules imagination, intuition, travel, and subconscious mind — a prominent Moon mount is found in creative writers, psychics, and those drawn to travel over water. Upper Mars (between Mercury and Moon mounts) represents moral courage and resistance; Lower Mars (between Jupiter and Venus) represents physical courage and aggression. The Plain of Mars (center of the palm) indicates resilience and temperament — a firm plain shows the ability to endure hardship with equanimity.', category: 'palmistry', topic: 'mounts_palm', source: 'Samudrika Shastra' },

  // ─── Finger Analysis ─────────────────────────────────────────────────────
  { text: 'The Thumb (Angushtha) is the most important finger in Hast Rekha Vigyan. Its top phalanx represents willpower, the second phalanx represents logic and reasoning. A long, well-formed thumb indicates strong determination and leadership, while a short thumb suggests impressionability and emotional decision-making. The Index Finger (Tarjani) represents ambition, ego, authority, and Jupiter\'s influence — a long index finger reaching the middle of the top phalanx of the middle finger indicates a commanding, ambitious personality. The Middle Finger (Madhyama) represents responsibility, Saturn\'s discipline, and boundaries. A balanced middle finger shows wisdom and duty; an excessively long one indicates melancholy and isolation.', category: 'palmistry', topic: 'finger_analysis', source: 'Hast Rekha Vigyan' },
  { text: 'The Ring Finger (Anamika) represents creativity, emotional expression, and Sun\'s influence — when it is as long as or longer than the index finger, it indicates a strong artistic temperament and risk-taking nature. The Little Finger (Kanishthika) governs communication, eloquence, and Mercury\'s energy — a long little finger reaching beyond the top phalanx of the ring finger denotes exceptional persuasion skills and business acumen. Finger shapes also carry meaning: pointed tips indicate idealism and psychic sensitivity, conical tips show artistic and creative ability, square tips reveal practicality and order, and spatulate (flared) tips signify energy, originality, and a love of action and exploration.', category: 'palmistry', topic: 'finger_shapes', source: 'Hast Rekha Vigyan' },

  // ─── Hand Shapes ─────────────────────────────────────────────────────────
  { text: 'Hand shape classification reveals fundamental temperament. Earth Hands have square palms and short fingers, indicating a practical, grounded, and dependable nature — these individuals prefer tangible results and work with their hands. Air Hands have square palms with long fingers, showing intellectual curiosity, strong communication skills, and a tendency to overthink. Water Hands feature long palms with long fingers, revealing deep emotional sensitivity, artistic talent, intuition, and vulnerability to stress. Fire Hands have long palms with short fingers, denoting energy, ambition, charisma, and natural leadership — these individuals are action-oriented risk-takers who inspire others but may lack patience for detail.', category: 'palmistry', topic: 'hand_shapes', source: 'Samudrika Shastra' },

  // ─── Special Markings ────────────────────────────────────────────────────
  { text: 'Stars on the palm are powerful markings indicating sudden, significant events — a star on the Mount of Jupiter brings unexpected fame or leadership opportunity, on the Mount of Apollo it indicates brilliant success in arts, while a star on the Mount of Saturn warns of fatalistic events. Crosses generally indicate obstacles or turning points; however, a cross between the Head and Heart Lines (the Mystic Cross) denotes strong intuitive and occult abilities. Islands on any line weaken its quality, creating periods of difficulty — on the Heart Line they indicate emotional distress, on the Head Line they suggest mental strain. Chains on a line indicate persistent struggles in that line\'s domain throughout the chained portion.', category: 'palmistry', topic: 'special_markings_1', source: 'Samudrika Shastra' },
  { text: 'Squares are protective markings that shield against danger wherever they appear — a square on a break in any line repairs and mitigates the damage of that break. Triangles indicate intellectual achievement and success through mental effort; a triangle on the Mount of Jupiter shows diplomatic skill, while one on the Mount of Mercury indicates scientific aptitude. Grilles (crosshatch patterns) on any mount dissipate that mount\'s energy, causing confusion and obstacles in its domain. Tridents are among the most auspicious markings — a trident at the end of any line magnifies its positive qualities threefold, and a trident on the Mount of Jupiter is considered one of the greatest signs of fortune, leadership, and spiritual attainment in Samudrika Shastra.', category: 'palmistry', topic: 'special_markings_2', source: 'Samudrika Shastra' },
];
