/**
 * Panchang Knowledge — sourced from Surya Siddhanta, Muhurta Chintamani
 */
export const PANCHANG_DATA = [
  // ─── Overview ─────────────────────────────────────────────────────────────
  { text: 'Panchang (Panchangam) literally means "five limbs" and refers to the five elements of the Hindu calendar: Tithi (lunar day), Vara (weekday), Nakshatra (lunar mansion), Yoga (luni-solar combination), and Karana (half-tithi). It is the foundation of Vedic timekeeping and is consulted for determining auspicious moments (Muhurat), festivals, vratas (fasts), and daily activities. A Panchang is calculated based on the positions of Sun and Moon relative to Earth.', category: 'panchang', topic: 'overview', source: 'Surya Siddhanta' },

  // ─── Tithis ───────────────────────────────────────────────────────────────
  { text: 'Tithi is the lunar day, determined by the angular distance between Sun and Moon (each 12° increment = 1 Tithi). There are 30 Tithis in a lunar month: 15 in Shukla Paksha (waxing, Pratipada to Purnima) and 15 in Krishna Paksha (waning, Pratipada to Amavasya). Each Tithi has a ruling deity and planet. Tithis are classified into 5 groups: Nanda (1,6,11), Bhadra (2,7,12), Jaya (3,8,13), Rikta (4,9,14), Purna (5,10,15). Nanda and Jaya tithis are generally auspicious; Rikta tithis should be avoided for auspicious work.', category: 'panchang', topic: 'tithi_overview', source: 'Surya Siddhanta' },

  { text: 'Shukla Paksha Tithis (waxing moon): Pratipada (1st) — new beginnings, ruled by Agni. Dwitiya (2nd) — foundation laying, ruled by Brahma. Tritiya (3rd) — Akshaya Tritiya is most auspicious, ruled by Gauri. Chaturthi (4th) — Vinayaka Chaturthi, ruled by Ganesha. Panchami (5th) — education and learning, ruled by Nagas. Shashthi (6th) — ruled by Kartikeya, good for child-related ceremonies. Saptami (7th) — ruled by Surya, vehicle purchase favored. Ashtami (8th) — mixed, ruled by Rudra, Durga Ashtami. Navami (9th) — ruled by Durga, aggressive actions. Dashami (10th) — Vijaya Dashami, ruled by Dharma.', category: 'panchang', topic: 'tithi_shukla_1', source: 'Muhurta Chintamani' },

  { text: 'Shukla Paksha continued: Ekadashi (11th) — most sacred for Vishnu worship, fasting highly recommended, ruled by Vishwadeva. No food grains should be consumed. Dwadashi (12th) — breaking of Ekadashi fast, ruled by Vishnu. Trayodashi (13th) — ruled by Kamadeva, good for love matters and Pradosha Vrata. Chaturdashi (14th) — ruled by Shiva, Maha Shivaratri falls here, good for Shiva worship but inauspicious for worldly activities. Purnima (15th, Full Moon) — most powerful Tithi, ruled by Moon/Soma, excellent for spiritual practices, charity, and Satyanarayan Puja. Guru Purnima, Buddha Purnima fall on this Tithi.', category: 'panchang', topic: 'tithi_shukla_2', source: 'Muhurta Chintamani' },

  { text: 'Krishna Paksha Tithis (waning moon) follow the same sequence from Pratipada (1st) to Chaturdashi (14th), ending with Amavasya (New Moon/30th). Krishna Paksha is generally considered less auspicious for new beginnings but powerful for: Tantric practices, ancestral worship (Pitru Tarpan), Kali and Bhairava worship, and dissolution of negative karma. Amavasya is sacred for ancestor worship and Pitru Tarpan. Mahalaya Amavasya (during Pitru Paksha) is the most important day for ancestral rites. Avoid starting new ventures on Amavasya.', category: 'panchang', topic: 'tithi_krishna', source: 'Muhurta Chintamani' },

  // ─── Yogas ────────────────────────────────────────────────────────────────
  { text: 'Yoga in Panchang is calculated from the combined longitude of Sun and Moon (each 13°20\' segment = 1 Yoga). There are 27 Yogas. Auspicious Yogas: Siddhi (16th — success), Shiva (20th — welfare), Sadhya (22nd — accomplishment), Shubha (23rd — good fortune), Shukla (24th — purity), Brahma (25th — creation), Indra (26th — power), Preeti (2nd — love), Ayushman (3rd — longevity), Saubhagya (4th — prosperity), Shobhana (5th — brilliance), Sukarma (7th — good deeds), Dhriti (8th — determination), Harshana (14th — joy).', category: 'panchang', topic: 'yoga_auspicious', source: 'Surya Siddhanta' },

  { text: 'Inauspicious Yogas to avoid for important activities: Vishkambha (1st — obstruction), Atiganda (6th — danger), Shoola (9th — pain/suffering), Ganda (10th — danger to life), Vyaghata (13th — destruction), Vajra (15th — hardness/conflict), Vyatipata (17th — great fall/calamity), Parigha (19th — obstruction/iron bar), Vaidhriti (27th — negative/split). Among these, Vyatipata and Vaidhriti are considered most inauspicious — no auspicious ceremony should be performed during these Yogas. Variyan (18th) is neutral.', category: 'panchang', topic: 'yoga_inauspicious', source: 'Surya Siddhanta' },

  // ─── Karanas ──────────────────────────────────────────────────────────────
  { text: 'Karana is half a Tithi — there are 2 Karanas per Tithi, totaling 60 per lunar month. Seven movable Karanas repeat 8 times: Bava (good for government work), Balava (auspicious for friendship), Kaulava (good for love/relationships), Taitila (good for wealth accumulation), Garaja (good for agriculture/farming), Vanija (good for commerce/trade), Vishti/Bhadra (inauspicious — avoid all auspicious work). Four fixed Karanas appear once each per month: Shakuni (end of Krishna Chaturdashi — good for healing), Chatushpada (first half of Amavasya — good for animal-related work), Nagava (second half of Amavasya — good for permanent tasks), Kimstughna (first half of Shukla Pratipada — good for auspicious work).', category: 'panchang', topic: 'karana', source: 'Surya Siddhanta' },

  { text: 'Vishti (Bhadra) Karana is the most important inauspicious Karana. It occurs 4 times in each Paksha (8 times per lunar month). During Vishti Karana: avoid travel, marriage, business deals, new ventures, lending/borrowing money, and entering a new house. Bhadra\'s mouth faces downward during Shukla Paksha (less harmful) and upward during Krishna Paksha (more harmful). Bhadra born from Sun is especially harmful. However, Vishti Karana is good for aggressive actions: warfare, surgery, demolition, and destruction of enemies.', category: 'panchang', topic: 'karana_vishti', source: 'Muhurta Chintamani' },

  // ─── Vara (Weekdays) ──────────────────────────────────────────────────────
  { text: 'The seven Varas (weekdays) and their ruling planets: Ravivaar (Sunday) — Sun — government work, father-related matters, health vitality, wearing Ruby. Somvaar (Monday) — Moon — mind, mother, water-related, agriculture, wearing Pearl. Mangalvaar (Tuesday) — Mars — property, surgery, courage, competition, wearing Red Coral. Budhvaar (Wednesday) — Mercury — education, business, communication, writing, wearing Emerald. Guruvaar (Thursday) — Jupiter — marriage, spirituality, teaching, law, wearing Yellow Sapphire. Shukravaar (Friday) — Venus — arts, romance, luxury, beauty, wearing Diamond. Shanivaar (Saturday) — Saturn — iron work, oil, service, discipline, wearing Blue Sapphire.', category: 'panchang', topic: 'vara', source: 'Surya Siddhanta' },

  { text: 'Vara-Tithi combinations create special effects: Sunday + Saptami = highly auspicious. Monday + Dwitiya or Ekadashi = excellent. Tuesday + Tritiya = Angaraki Chaturthi (very powerful for Ganesha worship). Wednesday + Ashtami = good for Budh worship. Thursday + Panchami = Guru Panchami, excellent for education. Friday + Navami = excellent for Durga worship. Saturday + Chaturdashi = Shani Pradosha, powerful for Saturn remedies. Avoid starting new work on Tuesday-Saturday combination with Rikta Tithis (4,9,14).', category: 'panchang', topic: 'vara_tithi_combo', source: 'Muhurta Chintamani' },

  // ─── Rahu Kaal ────────────────────────────────────────────────────────────
  { text: 'Rahu Kaal is a daily period of approximately 1.5 hours ruled by Rahu — considered highly inauspicious for starting new activities. The standard Rahu Kaal times (for sunrise at 6:00 AM): Sunday 4:30-6:00 PM, Monday 7:30-9:00 AM, Tuesday 3:00-4:30 PM, Wednesday 12:00-1:30 PM, Thursday 1:30-3:00 PM, Friday 10:30 AM-12:00 PM, Saturday 9:00-10:30 AM. Remember the mnemonic: "Mother Saw Father Wearing The Turban Slowly" (Mon-Sat order: 7:30, 9:00, 10:30, 12:00, 1:30, 3:00, 4:30). Activities already in progress before Rahu Kaal may continue.', category: 'panchang', topic: 'rahu_kaal', source: 'Muhurta Chintamani' },

  { text: 'Gulika Kaal (son of Saturn) and Yama Gandanta are two other inauspicious periods. Gulika Kaal is approximately 1.5 hours daily — avoid signing contracts, starting journeys, or medical procedures. Gulika Kaal times follow a different rotation than Rahu Kaal. Yama Gandanta is the junction point between Water and Fire signs (Cancer-Leo, Scorpio-Sagittarius, Pisces-Aries) — considered dangerous for births and new beginnings. When Moon transits these junctions (last 2 Ghatikas of a Water sign, first 2 of a Fire sign), it is Gandanta and must be avoided for auspicious work.', category: 'panchang', topic: 'gulika_yama', source: 'Muhurta Chintamani' },

  // ─── Special Days ─────────────────────────────────────────────────────────
  { text: 'Important Panchang-based observances: Ekadashi (11th Tithi) — fasting for Vishnu, occurs twice monthly. Pradosha (13th Tithi evening) — Shiva worship during twilight. Shivaratri (14th Krishna) — most sacred Shiva night. Chaturthi (4th Tithi) — Ganesha worship, Sankashti Chaturthi in Krishna Paksha. Purnima — Full Moon, Satyanarayan Puja, Guru worship. Amavasya — New Moon, ancestor worship. Sankranti — Sun\'s entry into a new sign, major festivals like Makar Sankranti. These dates are all determined from Panchang calculations.', category: 'panchang', topic: 'special_days', source: 'Dharma Sindhu' },

  { text: 'Adhik Maas (intercalary month) occurs approximately every 32.5 months when no Sankranti falls within a lunar month. During Adhik Maas: no marriages, upanayana, griha pravesh, or other Shodasha Samskaras should be performed. However, it is considered excellent for spiritual practices, charity, Vishnu worship, and reading sacred texts. Purushottam Maas (another name for Adhik Maas) is said to be Lord Vishnu\'s own month. Kshaya Maas (lost month) occurs rarely when two Sankrantis fall in one lunar month — it is considered inauspicious.', category: 'panchang', topic: 'adhik_maas', source: 'Dharma Sindhu' },
];
