/**
 * Planetary Knowledge — sourced from Brihat Parashara Hora Shastra, Jataka Parijata, Phaladeepika
 */
export const PLANET_DATA = [
  // ─── Sun (Surya) ──────────────────────────────────────────────────────────
  { text: 'Sun (Surya) is the king of the planetary cabinet. It represents the soul (Atma), father, government authority, vitality, ego, power, and leadership. Sun rules the sign Leo and is exalted in Aries (10 degrees) and debilitated in Libra. Its Mool Trikona is Leo 0-20 degrees. Sun is a natural malefic but a temporal benefic for Leo, Aries, and Sagittarius ascendants.', category: 'planets', topic: 'sun', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Sun governs the 1st house naturally and represents vitality, bones, heart, eyes (right eye), and the circulatory system. A strong Sun gives leadership ability, government favor, good health, and self-confidence. A weak or afflicted Sun causes ego problems, heart ailments, eye diseases, conflicts with authority, and strained relationship with father.', category: 'planets', topic: 'sun', source: 'Phaladeepika' },
  { text: 'Sun\'s dasha period lasts 6 years in the Vimshottari system. During Sun dasha, one may gain authority, government positions, recognition, and leadership roles. If Sun is well-placed, this period brings fame and power. If afflicted, it can bring ego conflicts, health issues related to heart and bones, and problems with father or authority figures.', category: 'planets', topic: 'sun_dasha', source: 'Brihat Parashara Hora Shastra' },

  // ─── Moon (Chandra) ───────────────────────────────────────────────────────
  { text: 'Moon (Chandra) is the queen of the planetary cabinet. It represents the mind (Manas), mother, emotions, feelings, imagination, fertility, and public image. Moon rules Cancer and is exalted in Taurus (3 degrees) and debilitated in Scorpio. Moon is a natural benefic when waxing (Shukla Paksha) and a malefic when waning (Krishna Paksha). The Nakshatra occupied by Moon at birth determines the Vimshottari Dasha sequence.', category: 'planets', topic: 'moon', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Moon governs mental health, emotional stability, memory, sleep patterns, and the fluid systems of the body including blood, lymph, and hormones. A strong Moon gives emotional balance, good memory, popularity, nurturing nature, and connection with mother. A weak Moon causes anxiety, depression, insomnia, emotional instability, and respiratory issues. Moon in water signs (Cancer, Scorpio, Pisces) amplifies emotional sensitivity.', category: 'planets', topic: 'moon', source: 'Jataka Parijata' },
  { text: 'Moon\'s dasha period lasts 10 years. During Moon dasha, emotional life, relationships with mother and women, mental peace, and public life come into focus. If Moon is strong and well-aspected, this period brings emotional fulfillment, popularity, travel, and mental growth. If afflicted, it brings mental disturbance, emotional turmoil, and issues with mother.', category: 'planets', topic: 'moon_dasha', source: 'Brihat Parashara Hora Shastra' },

  // ─── Mars (Mangal/Kuja) ───────────────────────────────────────────────────
  { text: 'Mars (Mangal/Kuja) is the commander-in-chief of the planetary army. It represents courage, energy, aggression, siblings (especially younger brothers), property, surgery, accidents, and martial arts. Mars rules Aries and Scorpio, is exalted in Capricorn (28 degrees) and debilitated in Cancer. Mars is a natural malefic that gives sharp energy, determination, and fighting spirit.', category: 'planets', topic: 'mars', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Mars governs muscles, blood, bone marrow, and the adrenal system. It rules courage, physical strength, and competitive spirit. A strong Mars gives leadership in military or sports, courage, property ownership, and technical skills. A weak Mars causes anger issues, accidents, blood disorders, skin diseases, and conflicts. Mars in the 1st, 4th, 7th, 8th, or 12th house from Lagna, Moon, or Venus creates Mangal Dosha (Kuja Dosha) affecting marriage.', category: 'planets', topic: 'mars', source: 'Phaladeepika' },
  { text: 'Mars\'s dasha period lasts 7 years. During Mars dasha, matters of property, siblings, courage, surgery, and physical vitality are highlighted. A well-placed Mars brings property gains, victory over enemies, surgical success, and physical strength. An afflicted Mars dasha brings accidents, conflicts, legal battles, blood-related diseases, and marital discord.', category: 'planets', topic: 'mars_dasha', source: 'Brihat Parashara Hora Shastra' },

  // ─── Mercury (Budha) ──────────────────────────────────────────────────────
  { text: 'Mercury (Budha) is the prince of the planetary cabinet. It represents intelligence, communication, commerce, education, writing, mathematics, and youthfulness. Mercury rules Gemini and Virgo, is exalted in Virgo (15 degrees) and debilitated in Pisces. Mercury is a natural benefic but becomes malefic when conjunct with malefics. It is the planet of duality, adaptability, and quick learning.', category: 'planets', topic: 'mercury', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Mercury governs the nervous system, speech, skin, intellect, and respiratory system. A strong Mercury gives excellent communication skills, business acumen, mathematical ability, and success in writing or media. A weak Mercury causes speech defects, skin diseases, nervous disorders, poor mathematical ability, and indecisiveness. Mercury is the significator of the 4th house (education) and 10th house (career).', category: 'planets', topic: 'mercury', source: 'Jataka Parijata' },

  // ─── Jupiter (Guru/Brihaspati) ────────────────────────────────────────────
  { text: 'Jupiter (Guru/Brihaspati) is the teacher (Guru) of the gods. It represents wisdom, knowledge, dharma, religion, law, expansion, wealth, children, and higher education. Jupiter rules Sagittarius and Pisces, is exalted in Cancer (5 degrees) and debilitated in Capricorn. Jupiter is the greatest natural benefic — its aspect on any house or planet brings protection and blessings.', category: 'planets', topic: 'jupiter', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Jupiter governs the liver, fat tissue, growth hormones, and the spiritual dimension of life. A strong Jupiter gives wisdom, religious inclination, good fortune, wealth, respect in society, and blessed children. A weak Jupiter causes financial instability, lack of wisdom, liver disorders, obesity, and difficulty with children. Jupiter aspects the 5th, 7th, and 9th houses from its position, making it uniquely protective.', category: 'planets', topic: 'jupiter', source: 'Phaladeepika' },
  { text: 'Jupiter\'s dasha period lasts 16 years — the longest positive dasha. During Jupiter dasha, wisdom, wealth, spirituality, children, and overall expansion are highlighted. A strong Jupiter dasha is the most blessed period — bringing marriage, children, wealth accumulation, spiritual growth, higher education, and societal respect. An afflicted Jupiter dasha brings false gurus, financial overextension, liver issues, and legal problems.', category: 'planets', topic: 'jupiter_dasha', source: 'Brihat Parashara Hora Shastra' },

  // ─── Venus (Shukra) ───────────────────────────────────────────────────────
  { text: 'Venus (Shukra) is the teacher of the demons (Asuras). It represents love, marriage, romance, beauty, art, luxury, vehicles, and sensual pleasures. Venus rules Taurus and Libra, is exalted in Pisces (27 degrees) and debilitated in Virgo. Venus is a strong natural benefic that brings comfort, wealth, and relationship harmony. It is the primary significator (karaka) of marriage and partnerships.', category: 'planets', topic: 'venus', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Venus governs the reproductive system, kidneys, face, and throat. A strong Venus gives a beautiful appearance, artistic talent, harmonious marriage, wealth, and luxury vehicles. A weak Venus causes relationship problems, sexual disorders, kidney issues, diabetes, and lack of material comfort. Venus is especially important for marriage timing — Venus dasha or antardasha often triggers marriage if the native is of marriageable age.', category: 'planets', topic: 'venus', source: 'Phaladeepika' },

  // ─── Saturn (Shani) ───────────────────────────────────────────────────────
  { text: 'Saturn (Shani) is the servant of the planetary cabinet. It represents discipline, karma, longevity, hardship, delay, detachment, servants, old age, and chronic disease. Saturn rules Capricorn and Aquarius, is exalted in Libra (20 degrees) and debilitated in Aries. Saturn is the greatest natural malefic but teaches the most important life lessons. Its transit through the 12th, 1st, and 2nd houses from natal Moon is called Sade Sati (7.5 years of Saturn), a period of transformation.', category: 'planets', topic: 'saturn', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Saturn governs bones, teeth, joints, tendons, and the aging process. A strong Saturn gives longevity, discipline, organizational ability, justice, and success through hard work. A weak Saturn causes chronic diseases, delays, depression, poverty, and problems with servants or employees. Saturn aspects the 3rd, 7th, and 10th houses from its position. Saturn\'s transit (Gochar) through different houses from Moon sign is one of the most important predictive tools.', category: 'planets', topic: 'saturn', source: 'Phaladeepika' },
  { text: 'Saturn\'s dasha period lasts 19 years — the longest dasha. During Saturn dasha, karmic lessons, discipline, career building, and endurance are tested. A well-placed Saturn dasha brings career advancement through hard work, real estate gains, organizational success, and spiritual maturity. An afflicted Saturn dasha brings chronic illness, delays, depression, legal issues, and separation from loved ones. Saturn rewards patience and punishes shortcuts.', category: 'planets', topic: 'saturn_dasha', source: 'Brihat Parashara Hora Shastra' },

  // ─── Rahu (North Node) ────────────────────────────────────────────────────
  { text: 'Rahu is the North Node of the Moon — a shadow planet (Chaya Graha) with no physical form. It represents obsession, illusion, foreign travel, technology, unconventional paths, sudden events, and material desires. Rahu acts like Saturn but with more intensity and unpredictability. Rahu is exalted in Taurus/Gemini and debilitated in Scorpio/Sagittarius (debated among scholars). Rahu amplifies the qualities of the sign and house it occupies.', category: 'planets', topic: 'rahu', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Rahu has no lordship over any sign but behaves like the lord of the sign it occupies. In modern times, Rahu represents technology, innovation, foreign connections, and unconventional success. A strong Rahu gives success in politics, technology, foreign lands, and research. A weak Rahu causes confusion, addiction, phobias, skin diseases, and involvement in scandals. Rahu\'s dasha lasts 18 years and can bring dramatic life changes.', category: 'planets', topic: 'rahu', source: 'Phaladeepika' },

  // ─── Ketu (South Node) ────────────────────────────────────────────────────
  { text: 'Ketu is the South Node of the Moon — the headless body of the demon. It represents spirituality, liberation (Moksha), past life karma, detachment, psychic abilities, and sudden losses. Ketu acts like Mars but with spiritual intensity. Ketu is exalted in Scorpio/Sagittarius and debilitated in Taurus/Gemini. Ketu gives results based on the sign, house, and planets it conjoins.', category: 'planets', topic: 'ketu', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Ketu governs the nervous system at a subtle level and represents past-life expertise. A strong Ketu gives spiritual wisdom, psychic abilities, healing powers, and detachment leading to liberation. A weak Ketu causes confusion, mysterious illnesses, accidents, and spiritual crisis. Ketu\'s dasha lasts 7 years and often brings spiritual awakening, sudden changes, or unexpected losses that redirect life purpose.', category: 'planets', topic: 'ketu', source: 'Phaladeepika' },
];
