/**
 * Remedy Knowledge — sourced from Lal Kitab, Mantra Shastra, Brihat Parashara Hora Shastra
 */
export const REMEDY_DATA = [
  // ─── Gemstone Remedies ────────────────────────────────────────────────────
  { text: 'Ruby (Manik) is the gemstone for Sun. Wear minimum 3 carats in gold on the ring finger of the right hand on Sunday during Shukla Paksha in Sun\'s hora. Best suited for Leo ascendant. Strengthens leadership, government relations, vitality, and father relationship. Contraindicated when Sun is a functional malefic for the ascendant. Never wear Ruby with Blue Sapphire, Diamond, or Hessonite.', category: 'remedy', topic: 'gemstone_sun', source: 'Lal Kitab' },
  { text: 'Pearl (Moti) is the gemstone for Moon. Wear minimum 4 carats in silver on the little finger of the right hand on Monday during Shukla Paksha. Best suited for Cancer ascendant. Strengthens mind, emotions, mother relationship, and sleep quality. Avoid if Moon is a malefic lord. Pearl is especially beneficial during Moon Dasha or when Moon is weak in the chart.', category: 'remedy', topic: 'gemstone_moon', source: 'Lal Kitab' },
  { text: 'Red Coral (Moonga) is the gemstone for Mars. Wear minimum 5 carats in gold or copper on the ring finger on Tuesday during Shukla Paksha. Best suited for Aries and Scorpio ascendants. Strengthens courage, property matters, blood health, and physical vitality. Essential remedy for Mangal Dosha when Mars is a functional benefic. Never combine with Emerald or Blue Sapphire.', category: 'remedy', topic: 'gemstone_mars', source: 'Lal Kitab' },
  { text: 'Emerald (Panna) is the gemstone for Mercury. Wear minimum 3 carats in gold on the little finger on Wednesday during Shukla Paksha. Best suited for Gemini and Virgo ascendants. Strengthens intellect, speech, business skills, and nervous system. Emerald is especially beneficial for students, writers, traders, and IT professionals. Contraindicated for Aries and Scorpio ascendants.', category: 'remedy', topic: 'gemstone_mercury', source: 'Lal Kitab' },
  { text: 'Yellow Sapphire (Pukhraj) is the gemstone for Jupiter. Wear minimum 3 carats in gold on the index finger on Thursday during Shukla Paksha. Best suited for Sagittarius and Pisces ascendants. Strengthens wisdom, wealth, children, marriage prospects, and spiritual growth. Yellow Sapphire is the most commonly recommended gemstone for marriage and financial prosperity. Avoid if Jupiter is a functional malefic.', category: 'remedy', topic: 'gemstone_jupiter', source: 'Lal Kitab' },
  { text: 'Diamond (Heera) is the gemstone for Venus. Wear minimum 0.5 carat in platinum or white gold on the middle finger on Friday during Shukla Paksha. Best suited for Taurus and Libra ascendants. Strengthens marriage, luxury, artistic talent, and reproductive health. White Sapphire or Zircon can be used as affordable substitutes. Never wear Diamond with Ruby or Pearl.', category: 'remedy', topic: 'gemstone_venus', source: 'Lal Kitab' },
  { text: 'Blue Sapphire (Neelam) is the gemstone for Saturn. This is the most powerful and potentially dangerous gemstone — MUST be tested for 3-7 days before wearing. Wear minimum 3 carats in silver or white gold on the middle finger on Saturday during Shukla Paksha. Best suited for Capricorn and Aquarius ascendants. When compatible, Blue Sapphire gives rapid results — career breakthrough, sudden wealth, and removal of obstacles. When incompatible, it can cause accidents, losses, and health issues.', category: 'remedy', topic: 'gemstone_saturn', source: 'Lal Kitab' },
  { text: 'Hessonite (Gomed) is the gemstone for Rahu. Wear minimum 5 carats in silver on the middle finger on Saturday or Wednesday during Krishna Paksha. Helps with Rahu Dasha difficulties, removes confusion and phobias, and supports success in technology and foreign dealings. Cat\'s Eye (Lehsuniya) is the gemstone for Ketu. Wear minimum 3 carats in gold on the little finger on Thursday. Helps with spiritual growth and removes sudden obstacles during Ketu Dasha.', category: 'remedy', topic: 'gemstone_rahu_ketu', source: 'Lal Kitab' },

  // ─── Mantra Remedies ──────────────────────────────────────────────────────
  { text: 'Planetary Mantras (Beej Mantras) for daily chanting: Sun — "Om Hraam Hreem Hraum Sah Suryaya Namah" (7000 times in 40 days). Moon — "Om Shraam Shreem Shraum Sah Chandraya Namah" (11000 times). Mars — "Om Kraam Kreem Kraum Sah Bhaumaya Namah" (10000 times). Mercury — "Om Braam Breem Braum Sah Budhaya Namah" (9000 times). Jupiter — "Om Graam Greem Graum Sah Gurave Namah" (19000 times). Venus — "Om Draam Dreem Draum Sah Shukraya Namah" (16000 times). Saturn — "Om Praam Preem Praum Sah Shanaischaraya Namah" (23000 times).', category: 'remedy', topic: 'beej_mantras', source: 'Mantra Shastra' },
  { text: 'Hanuman Chalisa is the universal remedy for all planetary afflictions, especially Saturn, Mars, and Rahu. Reciting Hanuman Chalisa daily (ideally 7 times on Tuesday and Saturday) provides protection from malefic influences, gives courage, removes obstacles, and strengthens the overall horoscope. For Sade Sati specifically, recite 11 times on Saturdays. Hanuman is considered the 11th Rudra and has power over all nine planets.', category: 'remedy', topic: 'hanuman_chalisa', source: 'Mantra Shastra' },

  // ─── Lal Kitab Remedies ───────────────────────────────────────────────────
  { text: 'Lal Kitab remedies (Totke) are simple, practical remedies that don\'t require elaborate rituals: For weak Sun — offer water to Sun at sunrise with copper vessel, keep a solid silver ball in pocket. For weak Moon — keep silver or water-filled glass near bedside, drink water from silver glass. For weak Mars — feed sweet chapati to dogs, carry red handkerchief. For weak Mercury — wash new green moong dal before eating, feed green grass to cows. For weak Jupiter — apply saffron tilak on forehead, wear yellow thread.', category: 'remedy', topic: 'lal_kitab_totke', source: 'Lal Kitab' },
  { text: 'Lal Kitab remedies for Saturn and shadow planets: For weak Saturn — donate mustard oil on Saturdays, feed black dog, offer water to Peepal tree. For Rahu afflictions — store rice and silver in a corner of the house, donate radish, keep a silver elephant figurine at home. For Ketu afflictions — feed jaggery to monkeys, donate blankets to poor, keep a dog as pet. These remedies are believed to work within 43 days of consistent practice.', category: 'remedy', topic: 'lal_kitab_totke_2', source: 'Lal Kitab' },

  // ─── Rudraksha Remedies ───────────────────────────────────────────────────
  { text: 'Rudraksha beads are powerful remedies based on their Mukhi (faces): 1 Mukhi — Sun remedy, extremely rare, gives enlightenment. 2 Mukhi — Moon remedy, emotional balance. 3 Mukhi — Mars remedy, confidence and energy. 4 Mukhi — Mercury remedy, intelligence and communication. 5 Mukhi — Jupiter remedy, most common, good for overall protection. 6 Mukhi — Venus remedy, relationship harmony. 7 Mukhi — Saturn remedy, wealth and fortune. 8 Mukhi — Rahu remedy, removes obstacles. 9 Mukhi — Ketu remedy, spiritual growth. Wear after proper energization (Prana Pratishtha).', category: 'remedy', topic: 'rudraksha', source: 'Mantra Shastra' },
];
