/**
 * Shadbala (Six-fold Strength) Knowledge — sourced from Brihat Parashara Hora Shastra
 * Six types of planetary strength for accurate interpretation
 */
export const SHADBALA_DATA = [
  { text: 'Shadbala (Six Strengths) is the comprehensive Vedic system for measuring planetary strength. The six components are: 1) Sthana Bala (positional strength), 2) Dig Bala (directional strength), 3) Kala Bala (temporal strength), 4) Cheshta Bala (motional strength), 5) Naisargika Bala (natural strength), 6) Drik Bala (aspectual strength). Total Shadbala is measured in Rupas (1 Rupa = 60 Virupas). A planet needs minimum Rupas to give full results.', category: 'shadbala', topic: 'shadbala_overview', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Sthana Bala (Positional Strength) has 5 sub-components: a) Uchcha Bala — strength from exaltation (max at exact exaltation degree, zero at debilitation), b) Saptavargaja Bala — strength from 7 divisional charts (Rashi, Hora, Drekkana, Saptamsha, Navamsa, Dwadashamsha, Trimshamsha), c) Ojha-Yugma Bala — odd/even sign strength, d) Kendradi Bala — planets in Kendras get 60 virupas, Panaphara 30, Apoklima 15, e) Drekkana Bala — based on decanate position.', category: 'shadbala', topic: 'sthana_bala', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Dig Bala (Directional Strength): Jupiter and Mercury are strongest in the 1st house (East). Sun and Mars are strongest in the 10th house (South). Saturn is strongest in the 7th house (West). Moon and Venus are strongest in the 4th house (North). A planet in its Dig Bala house gets 60 virupas; in the opposite house gets 0. This explains why Jupiter in the 1st house is so powerful (both Kendra and Dig Bala).', category: 'shadbala', topic: 'dig_bala', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Kala Bala (Temporal Strength) has multiple sub-components: a) Natonnata Bala — diurnal planets (Sun, Jupiter, Venus) strong during day; nocturnal (Moon, Mars, Saturn) strong at night; Mercury always strong, b) Paksha Bala — benefics strong in Shukla Paksha, malefics in Krishna, c) Tribhaga Bala — based on 1/3 divisions of day/night, d) Abda/Masa/Vara/Hora Lords — strength from being lord of year/month/day/hour, e) Ayana Bala — based on declination, f) Yuddha Bala — planetary war strength.', category: 'shadbala', topic: 'kala_bala', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Cheshta Bala (Motional Strength): This measures strength based on planetary motion. A retrograde planet gets maximum Cheshta Bala (60 virupas) because retrograde planets are closest to Earth and appear brightest. A planet at its fastest direct speed gets minimum. The order: Vakri (retrograde) > Anuvakri (entering retro) > Vikala (stationary) > Manda (slow) > Mandatara (slowest direct) > Sama (average speed) > Chara (fast direct) > Atichara (fastest). Sun and Moon have separate Cheshta Bala calculations.', category: 'shadbala', topic: 'cheshta_bala', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Naisargika Bala (Natural Strength) is fixed and does not change: Sun = 60, Moon = 51.43, Mars = 17.14, Mercury = 25.71, Jupiter = 34.29, Venus = 42.86, Saturn = 8.57 virupas. This represents the inherent luminosity/power ranking. The Sun is naturally the strongest planet. This explains why even a debilitated Sun has more inherent authority than a well-placed Saturn.', category: 'shadbala', topic: 'naisargika_bala', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Drik Bala (Aspectual Strength): Strength gained from aspects of other planets. Benefic aspects add to Drik Bala; malefic aspects subtract. Jupiter\'s full aspect (5th, 7th, 9th) on a planet gives maximum positive Drik Bala. Saturn\'s full aspect (3rd, 7th, 10th) gives negative Drik Bala. Mars\'s full aspect (4th, 7th, 8th) also gives negative. The net Drik Bala can be positive or negative.', category: 'shadbala', topic: 'drik_bala', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Minimum Shadbala requirements for planets to give full results (in Rupas): Sun = 6.5, Moon = 6.0, Mars = 5.0, Mercury = 7.0, Jupiter = 6.5, Venus = 5.5, Saturn = 5.0. Planets exceeding their minimum are considered strong. The Shadbala ratio (actual / required) indicates relative strength. A ratio above 1.0 means the planet is strong enough to deliver its promised results in dashas and transits.', category: 'shadbala', topic: 'shadbala_requirements', source: 'Brihat Parashara Hora Shastra' },
];
