/**
 * Zodiac Sign (Rashi) Knowledge — sourced from Brihat Parashara Hora Shastra, Saravali
 */
export const SIGN_DATA = [
  { text: 'Aries (Mesha) is the 1st sign, ruled by Mars. Element: Fire. Quality: Cardinal (Chara). Symbol: Ram. Body part: Head, face. Aries natives are courageous, energetic, pioneering, and competitive. They excel in leadership roles, military, sports, and entrepreneurship. Health concerns: headaches, migraines, fevers, blood pressure. Aries is the exaltation sign of Sun and debilitation of Saturn. Favorable colors: red, orange. Lucky number: 9.', category: 'signs', topic: 'aries', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Taurus (Vrishabha) is the 2nd sign, ruled by Venus. Element: Earth. Quality: Fixed (Sthira). Symbol: Bull. Body part: Throat, neck. Taurus natives value stability, luxury, beauty, and material comfort. They excel in banking, arts, agriculture, and hospitality. Health concerns: throat infections, thyroid issues, neck pain. Taurus is the exaltation sign of Moon and debilitation of Ketu (per some scholars). Favorable colors: green, pink. Lucky number: 6.', category: 'signs', topic: 'taurus', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Gemini (Mithuna) is the 3rd sign, ruled by Mercury. Element: Air. Quality: Dual (Dvisvabhava). Symbol: Twins. Body part: Arms, hands, lungs. Gemini natives are intellectual, communicative, versatile, and curious. They excel in writing, journalism, teaching, sales, and IT. Health concerns: respiratory issues, nervous disorders, shoulder problems. Gemini is the exaltation sign of Rahu (per some scholars). Favorable colors: yellow, green. Lucky number: 5.', category: 'signs', topic: 'gemini', source: 'Saravali' },
  { text: 'Cancer (Karka) is the 4th sign, ruled by Moon. Element: Water. Quality: Cardinal (Chara). Symbol: Crab. Body part: Chest, stomach, breasts. Cancer natives are nurturing, emotional, protective, and intuitive. They excel in hospitality, nursing, real estate, and food industry. Health concerns: digestive issues, chest problems, emotional disorders. Cancer is the exaltation sign of Jupiter and debilitation of Mars. Favorable colors: white, silver. Lucky number: 2.', category: 'signs', topic: 'cancer', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Leo (Simha) is the 5th sign, ruled by Sun. Element: Fire. Quality: Fixed (Sthira). Symbol: Lion. Body part: Heart, spine, upper back. Leo natives are authoritative, creative, generous, and dramatic. They excel in government, entertainment, management, and politics. Health concerns: heart diseases, spine issues, high blood pressure. Leo is the Mool Trikona of Sun. Favorable colors: gold, orange, red. Lucky number: 1.', category: 'signs', topic: 'leo', source: 'Saravali' },
  { text: 'Virgo (Kanya) is the 6th sign, ruled by Mercury. Element: Earth. Quality: Dual (Dvisvabhava). Symbol: Virgin. Body part: Intestines, digestive system. Virgo natives are analytical, detail-oriented, health-conscious, and service-minded. They excel in healthcare, accounting, editing, research, and quality control. Health concerns: digestive disorders, intestinal issues, anxiety. Virgo is the exaltation sign of Mercury and debilitation of Venus. Favorable colors: green, grey. Lucky number: 5.', category: 'signs', topic: 'virgo', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Libra (Tula) is the 7th sign, ruled by Venus. Element: Air. Quality: Cardinal (Chara). Symbol: Scales. Body part: Kidneys, lower back. Libra natives are diplomatic, artistic, partnership-oriented, and justice-seeking. They excel in law, diplomacy, fashion, art, and consulting. Health concerns: kidney problems, lower back pain, diabetes. Libra is the exaltation sign of Saturn and debilitation of Sun. Favorable colors: blue, white, pink. Lucky number: 6.', category: 'signs', topic: 'libra', source: 'Saravali' },
  { text: 'Scorpio (Vrishchika) is the 8th sign, ruled by Mars (and Ketu as co-ruler). Element: Water. Quality: Fixed (Sthira). Symbol: Scorpion. Body part: Reproductive organs, excretory system. Scorpio natives are intense, secretive, transformative, and deeply intuitive. They excel in research, occult sciences, surgery, investigation, and psychology. Health concerns: reproductive issues, piles, urinary disorders. Scorpio is the debilitation sign of Moon. Favorable colors: dark red, black. Lucky number: 9.', category: 'signs', topic: 'scorpio', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Sagittarius (Dhanu) is the 9th sign, ruled by Jupiter. Element: Fire. Quality: Dual (Dvisvabhava). Symbol: Archer. Body part: Hips, thighs. Sagittarius natives are philosophical, optimistic, freedom-loving, and adventurous. They excel in teaching, law, religion, publishing, and international trade. Health concerns: hip problems, liver issues, sciatica. Sagittarius is the Mool Trikona of Jupiter. Favorable colors: yellow, purple. Lucky number: 3.', category: 'signs', topic: 'sagittarius', source: 'Saravali' },
  { text: 'Capricorn (Makara) is the 10th sign, ruled by Saturn. Element: Earth. Quality: Cardinal (Chara). Symbol: Sea-goat. Body part: Knees, joints, bones. Capricorn natives are ambitious, disciplined, practical, and hardworking. They excel in government, corporate leadership, construction, mining, and agriculture. Health concerns: joint problems, knee injuries, skin diseases, depression. Capricorn is the exaltation sign of Mars and debilitation of Jupiter. Favorable colors: black, dark blue. Lucky number: 8.', category: 'signs', topic: 'capricorn', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Aquarius (Kumbha) is the 11th sign, ruled by Saturn (and Rahu as co-ruler). Element: Air. Quality: Fixed (Sthira). Symbol: Water-bearer. Body part: Ankles, calves, circulatory system. Aquarius natives are humanitarian, innovative, independent, and unconventional. They excel in technology, social work, science, aviation, and networking. Health concerns: circulatory problems, ankle injuries, nervous disorders. Favorable colors: blue, electric blue. Lucky number: 8.', category: 'signs', topic: 'aquarius', source: 'Saravali' },
  { text: 'Pisces (Meena) is the 12th sign, ruled by Jupiter (and Ketu as co-ruler). Element: Water. Quality: Dual (Dvisvabhava). Symbol: Two fish. Body part: Feet, lymphatic system. Pisces natives are compassionate, intuitive, artistic, and spiritually inclined. They excel in healing arts, music, film, charity work, and spiritual counseling. Health concerns: foot problems, immune system weakness, addictions, sleep disorders. Pisces is the exaltation sign of Venus and debilitation of Mercury. Favorable colors: sea green, lavender. Lucky number: 3.', category: 'signs', topic: 'pisces', source: 'Brihat Parashara Hora Shastra' },
];
