/**
 * Transit & Dasha Knowledge — sourced from Brihat Parashara Hora Shastra, Vimshottari Dasha
 */

interface SeedData {
  text: string;
  category: string;
  topic: string;
  source: string;
}

export const TRANSIT_DASHA_DATA: SeedData[] = [
  // ─── Mahadasha Periods (Sun through Ketu) ────────────────────────────────

  { text: 'Sun Mahadasha lasts 6 years in the Vimshottari system. During this period, the native gains authority, government recognition, and leadership roles. A strong Sun in Aries or Leo brings fame, political success, and vitality. An afflicted Sun causes ego clashes, strained relations with father, heart ailments, and loss of position. Remedies include Surya Namaskar at sunrise, offering water to the Sun, and reciting Aditya Hridayam Stotra daily for spiritual strength.', category: 'transits', topic: 'sun_dasha', source: 'Vimshottari Dasha' },

  { text: 'Moon Mahadasha lasts 10 years and governs emotional life, mental peace, and maternal relationships. When Moon is strong in Taurus or Cancer, this period brings popularity, emotional fulfillment, travel over water, and nurturing connections. A weak or afflicted Moon causes depression, anxiety, insomnia, and troubled relations with mother. Remedies include wearing a pearl on the little finger, worshipping Goddess Parvati on Mondays, and donating white items such as rice and milk on Mondays.', category: 'transits', topic: 'moon_dasha', source: 'Vimshottari Dasha' },

  { text: 'Mars Mahadasha lasts 7 years and activates courage, property matters, and physical vitality. A well-placed Mars in Capricorn or Aries bestows land acquisition, victory over enemies, and martial prowess. An afflicted Mars brings accidents, surgical interventions, blood disorders, and legal disputes with siblings. Remedies include reciting Hanuman Chalisa on Tuesdays, wearing red coral gemstone in copper, and donating red lentils and jaggery at Hanuman temples.', category: 'transits', topic: 'mars_dasha', source: 'Vimshottari Dasha' },

  { text: 'Mercury Mahadasha lasts 17 years and emphasizes intellect, communication, and commercial success. Strong Mercury in Virgo or Gemini confers excellence in writing, trade, education, and analytical thinking. Afflicted Mercury leads to speech disorders, nervous system weakness, skin ailments, and failed business ventures. Remedies include worshipping Lord Vishnu on Wednesdays, wearing emerald in gold on the little finger, and donating green moong dal and green cloth to scholars.', category: 'transits', topic: 'mercury_dasha', source: 'Vimshottari Dasha' },

  { text: 'Jupiter Mahadasha lasts 16 years and is considered the most auspicious Dasha period. Strong Jupiter in Cancer or Sagittarius brings wealth accumulation, spiritual growth, birth of children, higher education, and societal honor. Afflicted Jupiter causes financial overextension, liver ailments, false spiritual guidance, and legal entanglements. Remedies include wearing yellow sapphire (Pukhraj) in gold on the index finger, worshipping Lord Brihaspati, and donating turmeric and yellow cloth on Thursdays.', category: 'transits', topic: 'jupiter_dasha', source: 'Vimshottari Dasha' },

  { text: 'Venus Mahadasha lasts 20 years — the longest Dasha period — and governs love, marriage, luxury, and artistic expression. Strong Venus in Pisces or Taurus brings harmonious marriage, wealth, vehicles, and creative fulfillment. Afflicted Venus causes relationship breakdowns, reproductive health issues, kidney problems, and excessive indulgence. Remedies include reciting Shukra Mantra on Fridays, wearing diamond or white sapphire, and donating white silk and perfume to women.', category: 'transits', topic: 'venus_dasha', source: 'Vimshottari Dasha' },

  { text: 'Saturn Mahadasha lasts 19 years and tests the native through discipline, karmic debts, and endurance. Well-placed Saturn in Libra or Capricorn rewards patience with career stability, real estate gains, and organizational mastery. Afflicted Saturn brings chronic illness, depression, delays, poverty, and separation from loved ones. Remedies include worshipping Lord Shani on Saturdays, donating black sesame and mustard oil, feeding crows, and lighting a sesame oil lamp under a Peepal tree.', category: 'transits', topic: 'saturn_dasha', source: 'Vimshottari Dasha' },

  { text: 'Rahu Mahadasha lasts 18 years and brings dramatic, unconventional life changes. Strong Rahu in Taurus or Gemini grants success in technology, foreign lands, politics, and research. Afflicted Rahu triggers confusion, addiction, phobias, scandals, and sudden reversals of fortune. As a shadow planet, Rahu amplifies the qualities of its dispositor. Remedies include Rahu Shanti Puja, donating blue or black cloth on Saturdays, and reciting Durga Chalisa to counteract Rahu illusions.', category: 'transits', topic: 'rahu_dasha', source: 'Vimshottari Dasha' },

  { text: 'Ketu Mahadasha lasts 7 years and catalyzes spiritual awakening, detachment, and past-life karma resolution. Strong Ketu in Scorpio or Sagittarius grants psychic abilities, healing powers, and liberation from material bonds. Afflicted Ketu causes mysterious ailments, sudden losses, accidents, and spiritual crisis without direction. Remedies include worshipping Lord Ganesha, performing Ketu Shanti Homa, donating a multi-colored blanket, and reciting the Ganesha Atharvashirsha for clarity.', category: 'transits', topic: 'ketu_dasha', source: 'Vimshottari Dasha' },

  // ─── Major Transit Effects ────────────────────────────────────────────────

  { text: 'Saturn transit (Shani Gochar) through the twelve houses from Moon sign is the most significant transit in Vedic astrology. Saturn spends approximately 2.5 years in each sign. Transit through the 3rd, 6th, and 11th houses from Moon is favorable, granting victory over enemies, debt clearance, and income gains. Transit through the 1st, 4th, 7th, 8th, and 10th houses is challenging, bringing health concerns, domestic unrest, and career obstacles as described in Brihat Parashara.', category: 'transits', topic: 'saturn_transit', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Jupiter transit (Guru Gochar) through the houses from Moon sign brings expansion and blessings. Jupiter spends approximately one year in each sign. Transit through the 2nd, 5th, 7th, 9th, and 11th houses from Moon is highly auspicious, granting wealth increase, childbirth, marriage opportunities, and spiritual advancement. Jupiter transiting the 6th, 8th, and 12th houses may bring health expenses and spiritual trials but still offers protection through divine grace and wisdom growth.', category: 'transits', topic: 'jupiter_transit', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Rahu-Ketu transit axis shifts signs every 18 months, fundamentally altering collective and individual karmic themes. Rahu transiting the 3rd, 6th, 10th, or 11th house from Moon brings material gains, while Ketu simultaneously purifies the opposite house through detachment. The Rahu-Ketu axis through the 1st-7th houses transforms identity and partnerships, while the 4th-10th axis restructures home and career foundations. This nodal transit activates eclipse-sensitive degrees in the natal chart.', category: 'transits', topic: 'rahu_ketu_transit', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Retrograde planets in transit carry intensified karmic significance according to Parashara. Saturn retrograde transit delays results but deepens introspection and restructuring of life foundations. Jupiter retrograde turns wisdom inward, favoring spiritual study over material expansion. Mercury retrograde disrupts communication and commerce but encourages review of intellectual pursuits. Venus retrograde re-examines relationships and values. Mars retrograde redirects energy inward, cautioning against impulsive actions and surgical procedures.', category: 'transits', topic: 'retrograde_effects', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Solar and lunar eclipses (Grahan) have profound transit effects in Jyotish. A solar eclipse near natal Sun or in the Lagna sign triggers identity transformation and health vigilance. A lunar eclipse near natal Moon destabilizes emotions and mental equilibrium. Eclipses activating the Rahu-Ketu natal axis accelerate karmic events. Parashara advises avoiding major decisions during eclipse periods and performing Grahan Shanti Puja, chanting mantras, and donating food after the eclipse passes.', category: 'transits', topic: 'eclipse_impacts', source: 'Brihat Parashara Hora Shastra' },

  // ─── Dasha Interpretation ─────────────────────────────────────────────────

  { text: 'Antardasha (Bhukti) combinations within a Mahadasha refine the timing of events. The Antardasha lord modifies the Mahadasha lord results — a benefic Antardasha in a malefic Mahadasha mitigates suffering, while a malefic Antardasha in a benefic Mahadasha introduces temporary setbacks. The mutual relationship between Mahadasha and Antardasha lords (natural friendship, aspect, or conjunction in the natal chart) determines whether the sub-period brings harmony or conflict in results.', category: 'transits', topic: 'antardasha_combinations', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Dasha Sandhi is the critical transition period between two Mahadasha periods, typically lasting a few months before and after the changeover. This junction brings uncertainty, confusion, and mixed results as the outgoing planet relinquishes control and the incoming planet establishes influence. Parashara recommends performing Shanti Puja for both the departing and incoming Dasha lords during Sandhi. Natives often experience career shifts, health fluctuations, and emotional turbulence during this vulnerable transition.', category: 'transits', topic: 'dasha_sandhi', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Pratyantar Dasha (sub-sub-period) provides the finest level of timing in the Vimshottari system. While Mahadasha sets the broad theme and Antardasha narrows the focus, Pratyantar Dasha pinpoints the exact weeks or months when specific events manifest. A favorable Pratyantar lord activating Rajayoga combinations in the chart triggers sudden promotions or windfalls. Astrologers use Pratyantar Dasha with transit confirmation to precisely time marriage, childbirth, and career milestones.', category: 'transits', topic: 'pratyantar_dasha', source: 'Vimshottari Dasha' },

  // ─── Timing Predictions from Dasha ────────────────────────────────────────

  { text: 'Job change and career advancement timing is determined by the Dasha of the 10th house lord, planets in the 10th house, or the Dasha of planets aspecting the 10th house. Saturn or Sun Antardasha often triggers career shifts. The 6th house lord Dasha indicates service changes, while the 7th house lord Dasha may bring business partnerships. Confirm transit Saturn or Jupiter aspecting the 10th house during the Dasha period for reliable career prediction according to Parashara principles.', category: 'transits', topic: 'job_timing', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Marriage timing in Vedic astrology requires the Dasha or Antardasha of the 7th house lord, Venus, or planets connected to the 7th house. Jupiter transit over the 7th house or its lord confirms the timing. For women, Jupiter Dasha or Antardasha often triggers marriage; for men, Venus plays the primary role. Navamsha (D-9) chart activation during the running Dasha is essential. Parashara states that simultaneous Dasha activation and favorable transit of Jupiter ensures marriage manifestation.', category: 'transits', topic: 'marriage_timing', source: 'Brihat Parashara Hora Shastra' },

  { text: 'Wealth accumulation timing depends on the Dasha of the 2nd house lord (stored wealth), 11th house lord (income gains), or the Dasha of Dhana Yoga forming planets. Jupiter or Venus Antardasha within a favorable Mahadasha often brings financial windfalls. The Dasha of planets forming Lakshmi Yoga, Gajakesari Yoga, or Chandra-Mangal Yoga activates wealth potential. Transit Jupiter through the 2nd, 5th, 9th, or 11th house from Moon confirms the timing of financial gains as per classical texts.', category: 'transits', topic: 'wealth_timing', source: 'Brihat Parashara Hora Shastra' },
];
