/**
 * Yoga Knowledge — sourced from Brihat Parashara Hora Shastra, Jataka Parijata, Phaladeepika
 * Expanded: 76+ yogas with formation rules, effects, and cancellation conditions
 */
export const YOGA_DATA = [
  // ─── Pancha Mahapurusha Yogas (5 Great Person Yogas) ──────────────────────
  { text: 'Ruchaka Yoga forms when Mars is in its own sign (Aries/Scorpio) or exalted (Capricorn) in a Kendra house (1st, 4th, 7th, 10th). Effects: Strong physique, courageous, commander-like personality, success in military/police/sports, land ownership, leadership through strength and determination. The native becomes famous for their bravery and physical prowess. Cancellation: Mars combust, aspected by malefics, or in debilitated Navamsa.', category: 'yogas', topic: 'ruchaka_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Bhadra Yoga forms when Mercury is in its own sign (Gemini/Virgo) or exalted (Virgo) in a Kendra house. Effects: Exceptional intelligence, eloquent speech, success in business and academics, sharp wit, attractive personality. The native excels in communication, mathematics, astrology, or commerce. Cancellation: Mercury combust (within 14° of Sun), or retrograde in enemy sign.', category: 'yogas', topic: 'bhadra_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Hamsa Yoga forms when Jupiter is in its own sign (Sagittarius/Pisces) or exalted (Cancer) in a Kendra house. Effects: The most auspicious of the five yogas. The native is righteous, learned, spiritually evolved, respected by scholars, blessed with good children. They become teachers, priests, judges, or spiritual leaders. Cancellation: Jupiter combust, retrograde in enemy sign, or aspected by Saturn/Rahu.', category: 'yogas', topic: 'hamsa_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Malavya Yoga forms when Venus is in its own sign (Taurus/Libra) or exalted (Pisces) in a Kendra house. Effects: Beautiful appearance, artistic talent, luxurious lifestyle, happy marriage, refined tastes, success in arts and entertainment. Cancellation: Venus combust (within 10° of Sun), or in debilitated Navamsa, or aspected by malefics without benefic relief.', category: 'yogas', topic: 'malavya_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Shasha Yoga forms when Saturn is in its own sign (Capricorn/Aquarius) or exalted (Libra) in a Kendra house. Effects: Authority through hard work, command over workers, political power gained through discipline and patience. The native rises slowly but achieves lasting power. Cancellation: Saturn retrograde and aspected by Mars, or in debilitated Navamsa.', category: 'yogas', topic: 'shasha_yoga', source: 'Brihat Parashara Hora Shastra' },

  // ─── Wealth Yogas (Dhana Yogas) ───────────────────────────────────────────
  { text: 'Dhana Yoga (Wealth Yoga) forms when the lords of the 1st, 2nd, 5th, 9th, and 11th houses are connected through conjunction, aspect, or exchange. The strongest Dhana Yoga is when the 2nd and 11th lords are connected with the 5th or 9th lord. Jupiter\'s involvement amplifies wealth yoga effects. Multiple Dhana Yogas in a chart indicate enormous wealth potential.', category: 'yogas', topic: 'dhana_yoga', source: 'Jataka Parijata' },
  { text: 'Lakshmi Yoga forms when the 9th lord is strong and placed in a Kendra or Trikona, and Venus is in its own or exalted sign in a Kendra or Trikona. This yoga bestows immense wealth, luxury, beauty, and all forms of material comfort. The native is blessed by Goddess Lakshmi and attracts wealth effortlessly.', category: 'yogas', topic: 'lakshmi_yoga', source: 'Phaladeepika' },
  { text: 'Chandra-Mangal Yoga forms when Moon and Mars are conjunct in a house. Effects: Wealth through business, real estate, or mother\'s side. The native is enterprising and earns money through their own efforts. Best results in houses 2, 4, 10, or 11. Diminished if Moon is waning or Mars is debilitated.', category: 'yogas', topic: 'chandra_mangal_yoga', source: 'Phaladeepika' },

  // ─── Raja Yogas (Power Yogas) ─────────────────────────────────────────────
  { text: 'Raja Yoga forms when the lord of a Kendra (1st, 4th, 7th, 10th) and the lord of a Trikona (1st, 5th, 9th) are conjunct, mutually aspecting, or in exchange. The strongest is the conjunction of 9th and 10th lords (Dharma-Karmadhipati Yoga). This yoga gives power, authority, fame, and success in public life.', category: 'yogas', topic: 'raja_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Viparita Raja Yoga forms when the lords of Dusthana houses (6th, 8th, 12th) are placed in other Dusthana houses, or conjunct in a Dusthana. This paradoxical yoga gives success through adversity — the native rises to power after overcoming great obstacles. The destruction of enemies\' power becomes the native\'s gain.', category: 'yogas', topic: 'viparita_raja_yoga', source: 'Phaladeepika' },
  { text: 'Neecha Bhanga Raja Yoga forms when a debilitated planet gets cancellation through specific conditions: 1) Lord of the debilitation sign is in a Kendra from Lagna or Moon, 2) The exaltation lord of the debilitated planet aspects it, 3) The debilitated planet is conjunct its exaltation lord, 4) The debilitated planet is in Kendra. This yoga gives extraordinary rise from humble beginnings.', category: 'yogas', topic: 'neecha_bhanga_raja_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Dharma-Karmadhipati Yoga is the most powerful Raja Yoga. It forms when the 9th lord (Dharma/fortune) and 10th lord (Karma/career) are conjunct, mutually aspecting, or in exchange. Effects: The native achieves the highest position in their field, combines righteousness with action, gains both fame and fortune. This yoga produces CEOs, prime ministers, and great leaders.', category: 'yogas', topic: 'dharma_karmadhipati_yoga', source: 'Brihat Parashara Hora Shastra' },

  // ─── Gaja Kesari & Chandra Yogas ──────────────────────────────────────────
  { text: 'Gaja Kesari Yoga forms when Jupiter is in a Kendra from Moon (1st, 4th, 7th, 10th house from Moon). Effects: Wisdom, fame, prosperity, good reputation, leadership in community. The native is like a lion among elephants — commanding respect through knowledge. Cancellation: Jupiter debilitated, combust, or in enemy sign. Best when Jupiter is in own/exalted sign.', category: 'yogas', topic: 'gaja_kesari_yoga', source: 'Phaladeepika' },
  { text: 'Sunapha Yoga forms when any planet (except Sun, Rahu, Ketu) is in the 2nd house from Moon. Effects: Self-made wealth, good intellect, earns through own efforts. Mars gives wealth through courage; Mercury through intellect; Jupiter through wisdom; Venus through arts; Saturn through hard work.', category: 'yogas', topic: 'sunapha_yoga', source: 'Phaladeepika' },
  { text: 'Anapha Yoga forms when any planet (except Sun, Rahu, Ketu) is in the 12th house from Moon. Effects: Good health, virtuous character, fame, comfort in life. The specific planet determines the nature of fame and comfort.', category: 'yogas', topic: 'anapha_yoga', source: 'Phaladeepika' },
  { text: 'Durudhura Yoga forms when planets occupy both the 2nd and 12th houses from Moon (excluding Sun, Rahu, Ketu). Effects: Wealth, generous nature, fame, vehicles, enjoys all comforts. The native is well-supported from all sides and achieves balanced success.', category: 'yogas', topic: 'durudhura_yoga', source: 'Phaladeepika' },
  { text: 'Adhi Yoga forms when benefics (Mercury, Jupiter, Venus) occupy the 6th, 7th, and 8th houses from Moon. Effects: The native becomes a king or leader, commands respect, lives in comfort, defeats enemies easily. This is one of the most powerful yogas for worldly success.', category: 'yogas', topic: 'adhi_yoga', source: 'Phaladeepika' },

  // ─── Solar Yogas ──────────────────────────────────────────────────────────
  { text: 'Budhaditya Yoga forms when Sun and Mercury are conjunct in the same sign. Effects: Sharp intellect, communication skills, success in education, analytical ability. However, when Mercury is too close to Sun (within 3°, combust), the positive effects are diminished. Best results when Mercury is ahead of Sun (Morning Star position).', category: 'yogas', topic: 'budhaditya_yoga', source: 'Jataka Parijata' },
  { text: 'Vesi Yoga forms when any planet (except Moon, Rahu, Ketu) is in the 2nd house from Sun. Effects: Truthful, noble, prosperous. Mars in 2nd from Sun gives courage and wealth; Mercury gives intellect and business success; Jupiter gives wisdom and spirituality; Venus gives artistic talent; Saturn gives discipline and authority.', category: 'yogas', topic: 'vesi_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Vosi Yoga forms when any planet (except Moon, Rahu, Ketu) is in the 12th house from Sun. Effects: Learned, generous, skillful. The specific planet colors the nature of skills and generosity.', category: 'yogas', topic: 'vosi_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Ubhayachari Yoga forms when planets occupy both the 2nd and 12th houses from Sun (excluding Moon, Rahu, Ketu). Effects: The native is equal to a king, eloquent, handsome, and enjoys all luxuries of life. This is a very auspicious configuration.', category: 'yogas', topic: 'ubhayachari_yoga', source: 'Brihat Parashara Hora Shastra' },

  // ─── Spiritual/Knowledge Yogas ────────────────────────────────────────────
  { text: 'Saraswati Yoga forms when Jupiter, Venus, and Mercury occupy Kendras, Trikonas, or the 2nd house, and Jupiter is in its own, exalted, or friendly sign. Effects: Exceptional learning, mastery of arts and sciences, poetic ability, fame through knowledge, scholarly recognition. The native becomes a renowned scholar blessed by Goddess Saraswati.', category: 'yogas', topic: 'saraswati_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Brahma Yoga forms when Jupiter is in a Kendra, Venus is in the 9th, and Mercury is in a Kendra or Trikona with Jupiter. Effects: The native is deeply learned in scriptures, righteous, and gains fame through spiritual or philosophical knowledge.', category: 'yogas', topic: 'brahma_yoga', source: 'Jataka Parijata' },
  { text: 'Amala Yoga forms when a natural benefic (Jupiter, Venus, Mercury, or full Moon) is in the 10th house from Lagna or Moon. Effects: Pure fame, virtuous reputation, the native is known for good deeds and earns respect from all sections of society. The specific benefic determines the nature of fame.', category: 'yogas', topic: 'amala_yoga', source: 'Phaladeepika' },

  // ─── Nabhas Yogas (Formation Yogas based on planetary patterns) ────────────
  { text: 'Yupa Yoga forms when all planets are in 4 consecutive signs starting from a Kendra. Effects: The native is like a pillar of society — charitable, devoted to duty, fond of religious activities, performs sacrifices.', category: 'yogas', topic: 'yupa_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Shara Yoga (Arrow Yoga) forms when all planets are in 4 consecutive signs starting from a fixed sign (Taurus, Leo, Scorpio, Aquarius). Effects: The native is skilled in weapons/tools, a surgeon or mechanic, cruel in nature, involved in imprisoning others.', category: 'yogas', topic: 'shara_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Shakti Yoga (Power Yoga) forms when all planets are in 4 consecutive signs starting from a dual sign. Effects: The native is impoverished, lazy, lacking in achievement, but has specialized knowledge in one area.', category: 'yogas', topic: 'shakti_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Musala Yoga (Pestle Yoga) forms when all 7 planets occupy only fixed signs (Taurus, Leo, Scorpio, Aquarius). Effects: The native is proud, wealthy, learned, respected by the king/government, enjoys fame and status.', category: 'yogas', topic: 'musala_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Nala Yoga (Reed Yoga) forms when all 7 planets occupy only dual signs (Gemini, Virgo, Sagittarius, Pisces). Effects: Skilled in arts, limited wealth, attractive body, well-traveled, clever.', category: 'yogas', topic: 'nala_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Rajju Yoga (Rope Yoga) forms when all 7 planets occupy only movable signs (Aries, Cancer, Libra, Capricorn). Effects: Fond of travel, earns in foreign lands, cruel temperament, slim body.', category: 'yogas', topic: 'rajju_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Sarpa Yoga (Snake Yoga) forms when all 7 planets are in Apoklima houses (3rd, 6th, 9th, 12th). Effects: The native suffers from misery, cruelty, poverty, depends on others for food, unhappy existence. This is a highly malefic configuration.', category: 'yogas', topic: 'sarpa_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Mala Yoga (Garland Yoga) forms when all benefics are in Kendras and malefics in 3rd, 6th, 11th. Effects: The native is like royalty — wealthy, fortunate, enjoys many vehicles, commands respect. This is extremely rare and auspicious.', category: 'yogas', topic: 'mala_yoga', source: 'Brihat Parashara Hora Shastra' },

  // ─── Parivartan (Exchange) Yogas ──────────────────────────────────────────
  { text: 'Maha Parivartana Yoga forms when lords of Kendras or Trikonas exchange signs. Example: Jupiter in Aries and Mars in Sagittarius. Effects: Excellent results of both houses, creates Raja Yoga-like effects, powerful combination for success and authority.', category: 'yogas', topic: 'maha_parivartana_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Dainya Parivartana Yoga forms when a Dusthana lord (6th, 8th, 12th) exchanges with a Kendra/Trikona lord. Effects: Highly inauspicious, causes suffering related to both houses. The native faces obstacles, health issues, and setbacks related to the houses involved.', category: 'yogas', topic: 'dainya_parivartana_yoga', source: 'Brihat Parashara Hora Shastra' },

  // ─── Special Yogas ────────────────────────────────────────────────────────
  { text: 'Gajakesari Yoga cancellation conditions: 1) Jupiter is debilitated (Capricorn), 2) Jupiter is combust (within 11° of Sun), 3) Jupiter is in an enemy sign (Gemini, Virgo), 4) Jupiter is aspected only by malefics without benefic relief, 5) Jupiter is retrograde in a dusthana house. When cancelled, the yoga produces reduced or no results.', category: 'yogas', topic: 'gaja_kesari_cancellation', source: 'Phaladeepika' },
  { text: 'Shakata Yoga forms when Jupiter is in the 6th, 8th, or 12th from Moon. Effects: Ups and downs in fortune, the native experiences cycles of success and failure. Wealth comes and goes like a cartwheel (shakata). This yoga is cancelled if Jupiter is in a Kendra from Lagna.', category: 'yogas', topic: 'shakata_yoga', source: 'Phaladeepika' },
  { text: 'Chaturmukha Yoga forms when Jupiter, Venus, Mercury, and Moon are in Kendras and none are debilitated. Effects: The native is like Brahma (four-faced god) — knowledgeable in all fields, respected by scholars, wealthy, and commands authority over a vast domain.', category: 'yogas', topic: 'chaturmukha_yoga', source: 'Jataka Parijata' },
  { text: 'Parvata Yoga forms when benefics are in Kendras and the 6th and 8th houses are either empty or occupied by benefics. Effects: The native is like a mountain — strong, wealthy, famous, generous, and a leader. They build lasting structures and institutions.', category: 'yogas', topic: 'parvata_yoga', source: 'Phaladeepika' },
  { text: 'Kahala Yoga forms when the 4th lord and Jupiter are in mutual Kendras from each other, and the Lagna lord is strong. Effects: The native is bold, courageous, and heads an army or organization. They are stubborn but effective leaders.', category: 'yogas', topic: 'kahala_yoga', source: 'Jataka Parijata' },

  // ─── Negative Yogas ───────────────────────────────────────────────────────
  { text: 'Kemadruma Yoga forms when there are no planets in the 2nd or 12th house from Moon, and Moon has no conjunction or aspect from benefics. Effects: Poverty despite good birth, mental distress, loneliness. Cancellation: Moon in a Kendra, aspected by Jupiter or Venus, conjunct a benefic, or planets in Kendras from Lagna. Many charts have Kemadruma cancelled (Bhanga).', category: 'yogas', topic: 'kemadruma_yoga', source: 'Phaladeepika' },
  { text: 'Daridra Yoga (Poverty Yoga) forms when the 11th lord is in the 6th, 8th, or 12th house, especially when afflicted by malefics. Effects: Financial struggles, inability to accumulate wealth, debts. Remedies include strengthening the 11th lord through gemstones, mantras, and charitable acts.', category: 'yogas', topic: 'daridra_yoga', source: 'Jataka Parijata' },
  { text: 'Grahan Yoga forms when Sun or Moon is conjunct Rahu or Ketu. Sun-Rahu = Surya Grahan Dosha (ego issues, father problems). Sun-Ketu = spiritual crisis. Moon-Rahu = Chandra Grahan Dosha (mental anxiety, mother issues). Moon-Ketu = detachment, spiritual inclination but emotional void.', category: 'yogas', topic: 'grahan_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Guru Chandal Yoga forms when Jupiter is conjunct Rahu. Effects: The native may be irreligious, break traditions, face issues with teachers/gurus. However, in modern context this yoga can give unconventional wisdom, success in foreign lands, and innovation in traditional fields. Rahu amplifies Jupiter\'s significations in unpredictable ways.', category: 'yogas', topic: 'guru_chandal_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Shrapit Yoga forms when Saturn and Rahu are conjunct in any house. Effects: Karmic debt from past lives, obstacles in the house they occupy, delays and frustrations. The native must work through karmic lessons. Remedies: Shani-Rahu Shanti Puja, donation of black items on Saturday, worship of Lord Hanuman.', category: 'yogas', topic: 'shrapit_yoga', source: 'Lal Kitab' },
  { text: 'Angarak Yoga forms when Mars and Rahu are conjunct. Effects: Aggressive temperament, accidents, legal troubles, disputes over property. The native may face sudden violent events or conflicts. This yoga is especially dangerous in houses 1, 4, 7, 8. Remedies: Hanuman Puja, Mangal Shanti, avoid red coral without expert consultation.', category: 'yogas', topic: 'angarak_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Chandal Yoga forms when Jupiter is conjunct Ketu. Effects: Spiritual crisis, confusion about dharma, problems with children. However, this can also give deep spiritual insight and detachment from materialism. The native may be drawn to asceticism or unconventional spiritual paths.', category: 'yogas', topic: 'chandal_yoga', source: 'Jataka Parijata' },
  { text: 'Vish Yoga (Poison Yoga) forms when Saturn and Moon are conjunct. Effects: Depression, emotional coldness, delayed marriage, mother\'s health issues, pessimistic outlook. The native\'s mind (Moon) is restricted by Saturn\'s heaviness. Remedies: Silver ring, Chandra Shanti, milk donation on Mondays.', category: 'yogas', topic: 'vish_yoga', source: 'Phaladeepika' },
  { text: 'Punaraphoo Yoga forms when Saturn aspects Moon or is conjunct Moon, OR when Saturn aspects the 7th house or its lord. Effects: Delayed marriage, sometimes multiple relationships before settling. The native finds their ideal partner later in life (after Saturn matures at 36). This yoga gives a stable and long-lasting marriage when it finally happens.', category: 'yogas', topic: 'punaraphoo_yoga', source: 'Jataka Parijata' },
];
