/**
 * Yoga Knowledge — sourced from Brihat Parashara Hora Shastra, Jataka Parijata, Phaladeepika
 */
export const YOGA_DATA = [
  // ─── Pancha Mahapurusha Yogas (5 Great Person Yogas) ──────────────────────
  { text: 'Ruchaka Yoga forms when Mars is in its own sign (Aries/Scorpio) or exalted (Capricorn) in a Kendra house (1st, 4th, 7th, 10th). Effects: Strong physique, courageous, commander-like personality, success in military/police/sports, land ownership, leadership through strength and determination. The native becomes famous for their bravery and physical prowess.', category: 'yogas', topic: 'ruchaka_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Bhadra Yoga forms when Mercury is in its own sign (Gemini/Virgo) or exalted (Virgo) in a Kendra house. Effects: Exceptional intelligence, eloquent speech, success in business and academics, sharp wit, attractive personality. The native excels in communication, mathematics, astrology, or commerce. They become advisors to kings (modern: consultants to leaders).', category: 'yogas', topic: 'bhadra_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Hamsa Yoga forms when Jupiter is in its own sign (Sagittarius/Pisces) or exalted (Cancer) in a Kendra house. Effects: The most auspicious of the five yogas. The native is righteous, learned, spiritually evolved, respected by scholars, blessed with good children, and enjoys all comforts of life. They become teachers, priests, judges, or spiritual leaders.', category: 'yogas', topic: 'hamsa_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Malavya Yoga forms when Venus is in its own sign (Taurus/Libra) or exalted (Pisces) in a Kendra house. Effects: Beautiful appearance, artistic talent, luxurious lifestyle, happy marriage, refined tastes, success in arts and entertainment. The native lives surrounded by beauty, comfort, and sensual pleasures. They may become successful artists, designers, or diplomats.', category: 'yogas', topic: 'malavya_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Shasha Yoga forms when Saturn is in its own sign (Capricorn/Aquarius) or exalted (Libra) in a Kendra house. Effects: Authority through hard work, command over workers and servants, village/city leadership, political power gained through discipline and patience. The native rises slowly but achieves lasting power and respect through perseverance.', category: 'yogas', topic: 'shasha_yoga', source: 'Brihat Parashara Hora Shastra' },

  // ─── Wealth Yogas (Dhana Yogas) ───────────────────────────────────────────
  { text: 'Dhana Yoga (Wealth Yoga) forms when the lords of the 1st, 2nd, 5th, 9th, and 11th houses are connected through conjunction, aspect, or exchange. The strongest Dhana Yoga is when the 2nd and 11th lords are connected with the 5th or 9th lord. Jupiter\'s involvement amplifies wealth yoga effects. Multiple Dhana Yogas in a chart indicate enormous wealth potential. Timing of wealth comes through Dasha/Antardasha of involved planets.', category: 'yogas', topic: 'dhana_yoga', source: 'Jataka Parijata' },
  { text: 'Lakshmi Yoga forms when the 9th lord is strong and placed in a Kendra or Trikona, and Venus is in its own or exalted sign in a Kendra or Trikona. This yoga bestows immense wealth, luxury, beauty, and all forms of material comfort. The native is blessed by Goddess Lakshmi and attracts wealth effortlessly. This is one of the most powerful wealth yogas.', category: 'yogas', topic: 'lakshmi_yoga', source: 'Phaladeepika' },

  // ─── Raja Yogas (Power Yogas) ─────────────────────────────────────────────
  { text: 'Raja Yoga forms when the lord of a Kendra (1st, 4th, 7th, 10th) and the lord of a Trikona (1st, 5th, 9th) are conjunct, mutually aspecting, or in exchange. The strongest Raja Yoga is the conjunction of the 9th and 10th lords (Dharma-Karmadhipati Yoga). This yoga gives power, authority, fame, and success in public life. The native may become a leader, politician, CEO, or person of great influence.', category: 'yogas', topic: 'raja_yoga', source: 'Brihat Parashara Hora Shastra' },
  { text: 'Viparita Raja Yoga forms when the lords of Dusthana houses (6th, 8th, 12th) are placed in other Dusthana houses, or when they are conjunct in a Dusthana. This paradoxical yoga gives success through adversity — the native rises to power after overcoming great obstacles, enemies, or losses. The destruction of enemies\' power becomes the native\'s gain.', category: 'yogas', topic: 'viparita_raja_yoga', source: 'Phaladeepika' },

  // ─── Spiritual/Knowledge Yogas ────────────────────────────────────────────
  { text: 'Gaja Kesari Yoga forms when Jupiter is in a Kendra from Moon (1st, 4th, 7th, 10th house from Moon). Effects: Wisdom, fame, prosperity, good reputation, leadership in community, and respect from learned people. The native is like a lion among elephants — commanding respect through knowledge and wisdom. This is one of the most common and beneficial yogas.', category: 'yogas', topic: 'gaja_kesari_yoga', source: 'Phaladeepika' },
  { text: 'Budhaditya Yoga forms when Sun and Mercury are conjunct in the same sign. Effects: Sharp intellect, communication skills, success in education, analytical ability, and fame through knowledge. However, when Mercury is too close to Sun (within 3 degrees, combust), the positive effects are diminished. Best results when Mercury is ahead of Sun (Morning Star position).', category: 'yogas', topic: 'budhaditya_yoga', source: 'Jataka Parijata' },
  { text: 'Saraswati Yoga forms when Jupiter, Venus, and Mercury occupy Kendras, Trikonas, or the 2nd house, and Jupiter is in its own, exalted, or friendly sign. Effects: Exceptional learning, mastery of arts and sciences, poetic ability, fame through knowledge, and scholarly recognition. The native becomes a renowned scholar, artist, or musician blessed by Goddess Saraswati.', category: 'yogas', topic: 'saraswati_yoga', source: 'Brihat Parashara Hora Shastra' },

  // ─── Negative Yogas ───────────────────────────────────────────────────────
  { text: 'Kemadruma Yoga forms when there are no planets in the 2nd or 12th house from Moon, and Moon has no conjunction or aspect from benefics. Effects: Poverty despite good birth, mental distress, loneliness, lack of support system. This yoga is cancelled if: Moon is in a Kendra, Moon is aspected by Jupiter or Venus, Moon is conjunct a benefic, or if planets are in Kendras from Lagna. Many charts have Kemadruma Yoga cancelled (Bhanga).', category: 'yogas', topic: 'kemadruma_yoga', source: 'Phaladeepika' },
  { text: 'Daridra Yoga (Poverty Yoga) forms when the 11th lord is in the 6th, 8th, or 12th house, especially when afflicted by malefics. Effects: Financial struggles, inability to accumulate wealth, debts, and loss of income. Remedies include strengthening the 11th lord through gemstones, mantras, and charitable acts. The yoga\'s intensity depends on the strength of affliction and whether benefic aspects provide relief.', category: 'yogas', topic: 'daridra_yoga', source: 'Jataka Parijata' },
];
